export interface Lied {
    book: string;
    number: number;
    name: string;
}

export const verzeichnis: Lied[] = [
    // Ich will dir danken! (g/G)
    { book: "Iwdd!", number: 1, name: "Holy, holy, holy! Lord God Almighty" },
    { book: "Iwdd!", number: 1, name: "Heilig, heilig, heilig, Gott, Du bist heilig" },
    { book: "Iwdd!", number: 2, name: "Heilig, heilig, heilig ist der Herr Zebaoth" },
    { book: "Iwdd!", number: 3, name: "Unser Vater in dem Himmel, dir allein" },
    { book: "Iwdd!", number: 4, name: "Himmlischer Vater, wir beten Dich an" },
    { book: "Iwdd!", number: 4, name: "Heavenly father, I appreciate You" },
    { book: "Iwdd!", number: 5, name: "Großer Gott, wir loben dich" },
    { book: "Iwdd!", number: 5, name: "Holy God, we praise thy name" },
    { book: "Iwdd!", number: 6, name: "Du großer Gott, wenn ich die Welt betrachte" },
    { book: "Iwdd!", number: 6, name: "O Lord, my God! When I in awesome wonder" },
    { book: "Iwdd!", number: 7, name: "Gott ist immer noch Gott" },
    { book: "Iwdd!", number: 8, name: "Vater, ich lieb Dich (Herrlich sei Dein Name)" },
    { book: "Iwdd!", number: 9, name: "El Shaddai (Deutsch)" },
    { book: "Iwdd!", number: 10, name: "Herr, du mein Gott, du bist gut" },
    { book: "Iwdd!", number: 11, name: "Gib Gott die Ehre (Ehre, Ehre sei Gott)" },
    { book: "Iwdd!", number: 12, name: "A Dieu soit la gloire (Gloire à Dieu)" },
    { book: "Iwdd!", number: 12, name: "O Gott, dir sei Ehre (Preist den Herrn)" },
    { book: "Iwdd!", number: 12, name: "To God be the glory (Praise the Lord)" },
    { book: "Iwdd!", number: 13, name: "Unser Gott, Dein Name sei gelobt (Alles machst Du neu)" },
    { book: "Iwdd!", number: 14, name: "Ewiger Gott, o ewiger Gott, du bist hoch zu loben" },
    { book: "Iwdd!", number: 15, name: "Du bist mein Gott, ich will dich preisen" },
    { book: "Iwdd!", number: 16, name: "Ich lobe meinen Gott von ganzem Herzen" },
    { book: "Iwdd!", number: 17, name: "Immanuel, Immanuel" },
    { book: "Iwdd!", number: 18, name: "Gott ist gegenwärtig" },
    { book: "Iwdd!", number: 19, name: "Father, we love You (Glorify Your name)" },
    { book: "Iwdd!", number: 19, name: "Thou art my God and I will praise Thee" },
    { book: "Iwdd!", number: 19, name: "Vater im Himmel, wir beten Dich an (Kanon)" },
    { book: "Iwdd!", number: 20, name: "Gott ist allmächtig, drum preiset ihn mein Herz" },
    { book: "Iwdd!", number: 21, name: "Wir danken unserm Gott, wir danken unserm Gott (Weil Er uns so liebt)" },
    { book: "Iwdd!", number: 22, name: "Let's talk about Jesus" },
    { book: "Iwdd!", number: 22, name: "Wir singen von Jesus" },
    { book: "Iwdd!", number: 23, name: "Frohlocket all mit lautem Schall und Widerhall" },
    { book: "Iwdd!", number: 24, name: "Crown Him with many crowns" },
    { book: "Iwdd!", number: 24, name: "Mit allen Kronen krönt das Lamm auf Gottes Thron" },
    { book: "Iwdd!", number: 25, name: "Es ist wahr, daß Jesus lebt, Halleluja" },
    { book: "Iwdd!", number: 26, name: "Praise Him, praise Him! Jesus, our blessed redeemer" },
    { book: "Iwdd!", number: 26, name: "Preist Ihn! Preist Ihn! Jesum, den treuen Erlöser" },
    { book: "Iwdd!", number: 27, name: "Du bist das Licht der Welt" },
    { book: "Iwdd!", number: 28, name: "Jesus Christus herrscht als König" },
    { book: "Iwdd!", number: 29, name: "Schönster Herr Jesu" },
    { book: "Iwdd!", number: 30, name: "Anbetung bringen wir dir, Jesus, Gotteslamm" },
    { book: "Iwdd!", number: 31, name: "Sein Nam' ist höher als jeder andre" },
    { book: "Iwdd!", number: 31, name: "His name is higher than any other" },
    { book: "Iwdd!", number: 32, name: "Ist's wirklich wahr, daß mir zugut der Heiland starb" },
    { book: "Iwdd!", number: 32, name: "And can it be that I should gain" },
    { book: "Iwdd!", number: 33, name: "Unerschöpflich strömt die Quelle (Dir sei Ehre)" },
    { book: "Iwdd!", number: 33, name: "When I saw the cleansing fountain (I will praise Him)" },
    { book: "Iwdd!", number: 34, name: "Wir sind eins in dem Geist und wir sind eins in dem Herrn" },
    { book: "Iwdd!", number: 35, name: "We are gathering together unto Him" },
    { book: "Iwdd!", number: 35, name: "Wir versammeln uns zu dir, o großer Gott" },
    { book: "Iwdd!", number: 36, name: "Kommt, stimmet alle jubelnd ein" },
    { book: "Iwdd!", number: 37, name: "Jesus, du, des Lebens Herr" },
    { book: "Iwdd!", number: 38, name: "Jesus, Dir gehört mein Leben und Lobpreis" },
    { book: "Iwdd!", number: 39, name: "Majesty, worship His Majesty" },
    { book: "Iwdd!", number: 39, name: "Majestät, herrliche Majestät" },
    { book: "Iwdd!", number: 40, name: "All die Fülle ist in dir, o Herr" },
    { book: "Iwdd!", number: 41, name: "Oh, sing to the Lord! Oh, sing God a new song" },
    { book: "Iwdd!", number: 41, name: "Kommt, singt unserm Herrn! Ein neues Lied bringt Ihm" },
    { book: "Iwdd!", number: 41, name: "Cantad al Senor un cántico nuevo" },
    { book: "Iwdd!", number: 42, name: "Ich will dir danken (Gott, mein Herr, es ist mir ernst)" },
    { book: "Iwdd!", number: 43, name: "Groß ist dein Name, Herr, wir loben dich (Er selber, Gottes Sohn)" },
    { book: "Iwdd!", number: 44, name: "Lob, meine Seel, den Herrn" },
    { book: "Iwdd!", number: 45, name: "Für dich sei ganz mein Herz und Leben (Ich bete an die Macht der Liebe)" },
    { book: "Iwdd!", number: 46, name: "His name is Wonderful" },
    { book: "Iwdd!", number: 46, name: "Sein Nam' heißt Wunderbar" },
    { book: "Iwdd!", number: 47, name: "Thou art worthy, Thou art worthy" },
    { book: "Iwdd!", number: 47, name: "Du bist würdig, Du bist würdig" },
    { book: "Iwdd!", number: 48, name: "Lobe den Herren, den mächtigen König der Ehren" },
    { book: "Iwdd!", number: 49, name: "Du meine Seele, singe" },
    { book: "Iwdd!", number: 50, name: "Auf, Christen, stimmt ein Loblied an" },
    { book: "Iwdd!", number: 51, name: "Nie mehr wirst Du von uns weichen" },
    { book: "Iwdd!", number: 52, name: "Es beten dich an, die im Himmel, die auf der Erde" },
    { book: "Iwdd!", number: 53, name: "Halleluja, Halleluja! Jesus Christus, wir loben Dich" },
    { book: "Iwdd!", number: 54, name: "I will sing of the mercies of the Lord" },
    { book: "Iwdd!", number: 54, name: "Ich will singen von der Gnade meines Herrn" },
    { book: "Iwdd!", number: 55, name: "O lasst uns mit Jauchzen erheben" },
    { book: "Iwdd!", number: 56, name: "Juble, mein Herz, ich habe den Heiland gefunden" },
    { book: "Iwdd!", number: 57, name: "O daß ich tausend Zungen hätte" },
    { book: "Iwdd!", number: 58, name: "Lob und Dank, Lob und Dank" },
    { book: "Iwdd!", number: 59, name: "Vergiss nicht zu danken" },
    { book: "Iwdd!", number: 60, name: "Herr, Du hast Großes an uns hier getan (Herrlichkeit Dir, Jesu, allein)" },
    { book: "Iwdd!", number: 61, name: "Unser Mund, der ist voll Jubel" },
    { book: "Iwdd!", number: 62, name: "Halleluja, Halleluja! Singt und jubelt eurem Herrn (Singt Halleluja)" },
    { book: "Iwdd!", number: 63, name: "Nun danket alle Gott" },
    { book: "Iwdd!", number: 63, name: "Now thank we all our God" },
    { book: "Iwdd!", number: 64, name: "O Gott, sei gelobt für die Liebe im Sohn (Halleluja, sei gepriesen)" },
    { book: "Iwdd!", number: 65, name: "Amazing Grace (Amazing grace, how sweet the sound, that saved a wretch like me.)" },
    { book: "Iwdd!", number: 65, name: "O Gnade Gottes, wunderbar" },
    { book: "Iwdd!", number: 66, name: "Ich singe dir mit Herz und Mund" },
    { book: "Iwdd!", number: 67, name: "Sing mit mir ein Halleluja (Für die Ruhe in der Nacht)" },
    { book: "Iwdd!", number: 68, name: "O, hätt ich tausend Zungen nur" },
    { book: "Iwdd!", number: 69, name: "Ich will Dir danken, Herr (Sei erhoben, o Gott)" },
    { book: "Iwdd!", number: 69, name: "Je t'exalterai, Seigneur (Seigneur, élève toi)" },
    { book: "Iwdd!", number: 69, name: "I will give thanks to Thee (Be exalted, o God)" },
    { book: "Iwdd!", number: 70, name: "Danke, mein Vater, für alles, was Du schenkst" },
    { book: "Iwdd!", number: 71, name: "Verlasst euch stets auf den Herrn, denn der Herr ist ein ewiger Fels (Kanon)" },
    { book: "Iwdd!", number: 72, name: "Dass du mich einstimmen lässt in deinen Jubel, o Herr" },
    { book: "Iwdd!", number: 73, name: "Die Herrlichkeit des Herrn bleibe ewiglich (Kanon)" },
    { book: "Iwdd!", number: 73, name: "Let the glory of the Lord endure forever" },
    { book: "Iwdd!", number: 74, name: "Wüst ist das Land (Dankt dem Herrn Zebaoth)" },
    { book: "Iwdd!", number: 75, name: "Bleibend ist deine Treu" },
    { book: "Iwdd!", number: 75, name: "Great is Thy faithfulness" },
    { book: "Iwdd!", number: 76, name: "Dir, Herr, sei das Lob, das aus der Tiefe zu Dir dringt" },
    { book: "Iwdd!", number: 77, name: "Blagadarim Gaspodj" },
    { book: "Iwdd!", number: 77, name: "Jesus, wir danken Dir, Jesus, wir danken Dir" },
    { book: "Iwdd!", number: 78, name: "Steht auf und lobt unsern Gott" },
    { book: "Iwdd!", number: 79, name: "Lobet und preiset, ihr Völker, den Herrn" },
    { book: "Iwdd!", number: 80, name: "Lob, Ehr und Preis dir, Gottes Lamm" },
    { book: "Iwdd!", number: 81, name: "Danke, Herr Jesus (Allen Kummer, alle Sorgen sag ich dir, mein Herr und Gott)" },
    { book: "Iwdd!", number: 82, name: "Jesus, höchster Name" },
    { book: "Iwdd!", number: 82, name: "Jesus, name above all names" },
    { book: "Iwdd!", number: 83, name: "Er ist der Friedefürst und der allmächtge Gott" },
    { book: "Iwdd!", number: 84, name: "Jesus, Dir nur will ich singen (Ehre, Ehre, Preis, Anbetung)" },
    { book: "Iwdd!", number: 85, name: "Wohl dem, der nicht wandelt" },
    { book: "Iwdd!", number: 86, name: "Der Herr, mein Hirte, führet mich" },
    { book: "Iwdd!", number: 87, name: "Denn du bist groß, ein Gott, der Wunder tut" },
    { book: "Iwdd!", number: 88, name: "Lobe den Herrn, meine Seele, und Seinen heiligen Namen" },
    { book: "Iwdd!", number: 89, name: "Bei Dir ist die Quelle des Lebens" },
    { book: "Iwdd!", number: 90, name: "Das ist meine Freude (Aber das ist meine Freude, dass ich mich zu Gott halte)" },
    { book: "Iwdd!", number: 91, name: "Der Herr denkt an uns" },
    { book: "Iwdd!", number: 92, name: "Psalm 150 (Halleluja! Lobet Gott in Seinem Heiligtum)" },
    { book: "Iwdd!", number: 93, name: "Seid still und erkennt, dass ich Gott bin" },
    { book: "Iwdd!", number: 94, name: "Dennoch bleibe ich bei Dir" },
    { book: "Iwdd!", number: 94, name: "I'll be with You, You will guide me" },
    { book: "Iwdd!", number: 95, name: "Der Herr ist mein Licht und mein Heil" },
    { book: "Iwdd!", number: 96, name: "Ich trau auf Dich, oh Herr" },
    { book: "Iwdd!", number: 97, name: "Und dennoch bleibe ich stets bei Dir" },
    { book: "Iwdd!", number: 98, name: "Dein Wort ist meines Fußes Leuchte" },
    { book: "Iwdd!", number: 99, name: "Groß und wunderbar" },
    { book: "Iwdd!", number: 100, name: "Verlasst euch stets auf den Herrn" },
    { book: "Iwdd!", number: 101, name: "O for a thousand tongues to sing" },
    { book: "Iwdd!", number: 101, name: "Wo ist solch ein Gott? (Lei lei lei lei lei...)" },
    { book: "Iwdd!", number: 102, name: "Die dem Herrn vertrauen, schöpfen neue Kraft" },
    { book: "Iwdd!", number: 103, name: "Wenn mein Volk, über das mein Name genannt ist" },
    { book: "Iwdd!", number: 104, name: "Herr, dein Wort, die edle Gabe" },
    { book: "Iwdd!", number: 105, name: "Selig sind, die reinen Herzens sind" },
    { book: "Iwdd!", number: 106, name: "Seek ye first the kingdom of God" },
    { book: "Iwdd!", number: 106, name: "Trachtet zuerst nach Gottes Reich" },
    { book: "Iwdd!", number: 107, name: "Vater, ich will dich preisen" },
    { book: "Iwdd!", number: 108, name: "Ein neu' Gebot" },
    { book: "Iwdd!", number: 109, name: "Fürchte dich nicht, denn du bist mein" },
    { book: "Iwdd!", number: 110, name: "Die Güte des Herrn hat kein Ende" },
    { book: "Iwdd!", number: 111, name: "Ihr seid das Salz der Erde, ihr seid das Licht der Welt" },
    { book: "Iwdd!", number: 112, name: "Dein Wort kommt niemals leer zurück" },
    { book: "Iwdd!", number: 113, name: "Fels des Heils, geöffnet mir" },
    { book: "Iwdd!", number: 113, name: "Rock of ages, cleft for me" },
    { book: "Iwdd!", number: 114, name: "Wir wollen Deinen Tod verkünden" },
    { book: "Iwdd!", number: 115, name: "Lasst uns feiern das Mahl, das Er uns gab" },
    { book: "Iwdd!", number: 116, name: "Nehmt und esst" },
    { book: "Iwdd!", number: 117, name: "Jesus nahm das Brot und gab es Seinen Jüngern" },
    { book: "Iwdd!", number: 118, name: "Dem König, welcher Blut und Leben" },
    { book: "Iwdd!", number: 119, name: "Es ist ein Born, draus heilges Blut" },
    { book: "Iwdd!", number: 120, name: "Segen (Herr, segne uns und behüte uns)" },
    { book: "Iwdd!", number: 121, name: "Herr, mein ganzes Leben soll dir Ehre geben (Kanon)" },
    { book: "Iwdd!", number: 121, name: "Father, I adore You" },
    { book: "Iwdd!", number: 122, name: "Jesu Friede sei mit allen" },
    { book: "Iwdd!", number: 123, name: "Segne uns, o Herr" },
    { book: "Iwdd!", number: 124, name: "Jesus Christus segne dich" },
    { book: "Iwdd!", number: 125, name: "Gott, der Vater, kröne dich" },
    { book: "Iwdd!", number: 126, name: "Christus, der Herr aller Welt (Unser gemeinsamer Herr)" },
    { book: "Iwdd!", number: 127, name: "Wo zwei oder drei in meinem Namen versammelt sind" },
    { book: "Iwdd!", number: 128, name: "Friede, Friede, Friede sei mit dir (Nicht jenes Warten, wenn die Waffen schweigen...)" },
    { book: "Iwdd!", number: 129, name: "Du zeigst mir den Weg zum Leben" },
    { book: "Iwdd!", number: 130, name: "Geh unter der Gnade (Alte Stunden alte Tage...)" },
    { book: "Iwdd!", number: 131, name: "Siehe, ich mache alles neu" },
    { book: "Iwdd!", number: 132, name: "Himmel und Erde müssen vergehn (Kanon)" },
    { book: "Iwdd!", number: 133, name: "Herr, wir bitten: Komm und segne uns" },
    { book: "Iwdd!", number: 134, name: "Macht hoch die Tür" },
    { book: "Iwdd!", number: 135, name: "Advent ist es heut" },
    { book: "Iwdd!", number: 136, name: "Freue dich, Welt, dein König naht" },
    { book: "Iwdd!", number: 136, name: "Joy to the world" },
    { book: "Iwdd!", number: 137, name: "Wie soll ich dich empfangen" },
    { book: "Iwdd!", number: 138, name: "Mache dich auf und werde licht" },
    { book: "Iwdd!", number: 139, name: "In eine Welt voller Dunkelheit" },
    { book: "Iwdd!", number: 140, name: "O Du mein Trost und süßes Hoffen" },
    { book: "Iwdd!", number: 141, name: "Jesus ist kommen, Grund ewiger Freude" },
    { book: "Iwdd!", number: 142, name: "Die Nacht ist vorgedrungen" },
    { book: "Iwdd!", number: 143, name: "König der Herrlichkeit, König der Ehren" },
    { book: "Iwdd!", number: 144, name: "Tochter Zion, freue dich" },
    { book: "Iwdd!", number: 145, name: "So sehr liebt uns Gott, Er sandte Seinen Sohn" },
    { book: "Iwdd!", number: 146, name: "In der Nacht von Bethlehem" },
    { book: "Iwdd!", number: 147, name: "Der Heiland ist geboren (Freut euch von Herzen)" },
    { book: "Iwdd!", number: 148, name: "Schönster Herr Jesu (Kanon)" },
    { book: "Iwdd!", number: 149, name: "Unser Heiland ist nun da" },
    { book: "Iwdd!", number: 149, name: "Hark! the herald angels sing" },
    { book: "Iwdd!", number: 150, name: "Noel, Noel, Noel, Noel, born ist the king of Israel" },
    { book: "Iwdd!", number: 150, name: "Noel, Noel, Noel, Noel, Christ ist geboren" },
    { book: "Iwdd!", number: 151, name: "Stille Nacht, heilige Nacht" },
    { book: "Iwdd!", number: 152, name: "Ich steh an deiner Krippen hier" },
    { book: "Iwdd!", number: 153, name: "O come, all ye faithful" },
    { book: "Iwdd!", number: 153, name: "Herbei, o ihr Gläub'gen (Herbei, o ihr Gläubigen)" },
    { book: "Iwdd!", number: 154, name: "Freude, große Freude leuchtet aus der Nacht" },
    { book: "Iwdd!", number: 155, name: "Gloria, Gloria, Jesus, mein König, ist da" },
    { book: "Iwdd!", number: 156, name: "Fröhlich soll mein Herze springen" },
    { book: "Iwdd!", number: 157, name: "Danket, danket dem Herrn (Kanon)" },
    { book: "Iwdd!", number: 158, name: "Gott wurde arm für uns" },
    { book: "Iwdd!", number: 159, name: "Engel bringen frohe Kunde (Gloria in excelsis Deo)" },
    { book: "Iwdd!", number: 160, name: "O du fröhliche, o du selige" },
    { book: "Iwdd!", number: 161, name: "Ein Jahr geht nach dem andern hin" },
    { book: "Iwdd!", number: 162, name: "Das Jahr geht still zu Ende" },
    { book: "Iwdd!", number: 163, name: "In der Welt habt ihr Angst, aber seid getrost" },
    { book: "Iwdd!", number: 164, name: "Mit dem Herrn fang alles an" },
    { book: "Iwdd!", number: 165, name: "Mein Herr kennt den Weg, der vor mir liegt" },
    { book: "Iwdd!", number: 166, name: "Von guten Mächten wunderbar geborgen" },
    { book: "Iwdd!", number: 167, name: "Es eilt die Zeit (Komm, eh der letzte Tag versinkt)" },
    { book: "Iwdd!", number: 168, name: "Er geht voran, er hat's verheißen" },
    { book: "Iwdd!", number: 169, name: "O Haupt voll Blut und Wunden" },
    { book: "Iwdd!", number: 170, name: "O Du Lamm Gottes, das da getragen" },
    { book: "Iwdd!", number: 171, name: "Jesus Christus starb für mich" },
    { book: "Iwdd!", number: 172, name: "Für mich gingst Du nach Golgatha (Herr, Deine Liebe ist so groß)" },
    { book: "Iwdd!", number: 173, name: "Ich rief zu dem Herrn in meiner Angst" },
    { book: "Iwdd!", number: 174, name: "Eines wünsch ich mir vor allem andern" },
    { book: "Iwdd!", number: 175, name: "Was Gott nimmt, das reinigt Er" },
    { book: "Iwdd!", number: 176, name: "O Du Lamm Gottes, du hast auf Golgatha" },
    { book: "Iwdd!", number: 177, name: "Das Kreuz, es stehet fest (Halleluja, rühmt das Kreuz)" },
    { book: "Iwdd!", number: 178, name: "Alles, was atmen kann, lobe den Herrn" },
    { book: "Iwdd!", number: 179, name: "Schau ich zu deinem Kreuze hin" },
    { book: "Iwdd!", number: 180, name: "Kennst Du den Weg zum Kreuz auf Golgatha" },
    { book: "Iwdd!", number: 181, name: "When I survey the wondrous cross" },
    { book: "Iwdd!", number: 181, name: "Am Kreuz litt Er für mich (Jesus, mein Heiland, lebt)" },
    { book: "Iwdd!", number: 181, name: "Low in the grave He lay (Up from the grave He arose)" },
    { book: "Iwdd!", number: 182, name: "Freuet euch, das Grab ist leer" },
    { book: "Iwdd!", number: 183, name: "Lasst uns loben den Namen des Herrn (Kanon)" },
    { book: "Iwdd!", number: 184, name: "Auferstanden aus des Grabes Nacht (Und wir werden mit Ihm leben)" },
    { book: "Iwdd!", number: 185, name: "Er ist Herr" },
    { book: "Iwdd!", number: 185, name: "He is Lord, He is Lord" },
    { book: "Iwdd!", number: 186, name: "Seele, dein Heiland ist frei von den Banden (Jesus, dein Heiland, ist Sieger und lebt)" },
    { book: "Iwdd!", number: 187, name: "Mit Jauchzen freuet euch (Singt laut das Lied vom Sieg und Reich)" },
    { book: "Iwdd!", number: 188, name: "Jesus lebt, mit ihm auch ich" },
    { book: "Iwdd!", number: 189, name: "Er ist erstanden, Halleluja" },
    { book: "Iwdd!", number: 190, name: "Der Herr ist auferstanden (Er ist wahrhaftig auferstanden)" },
    { book: "Iwdd!", number: 191, name: "Seid nicht bekümmert" },
    { book: "Iwdd!", number: 192, name: "Christus ist auferstanden, wahrhaftig auferstanden" },
    { book: "Iwdd!", number: 193, name: "Jesus Christus ist der Sieger über Sünde, Tod und Teufel" },
    { book: "Iwdd!", number: 194, name: "Der Herr fährt auf gen Himmel mit frohem Jubelschall" },
    { book: "Iwdd!", number: 195, name: "Der Herr ist aufgefahren zum Thron der Herrlichkeit" },
    { book: "Iwdd!", number: 196, name: "Jesus ist Sieger, mit goldenen Lettern" },
    { book: "Iwdd!", number: 197, name: "Herr, befreie unsre Herzen, Dir zu danken" },
    { book: "Iwdd!", number: 198, name: "Mächtige Ströme des Segens" },
    { book: "Iwdd!", number: 198, name: "There shall be showers of blessing (Showers of blessing)" },
    { book: "Iwdd!", number: 199, name: "O Gott, o Geist, o Licht des Lebens" },
    { book: "Iwdd!", number: 200, name: "O komm, du Geist der Wahrheit" },
    { book: "Iwdd!", number: 201, name: "Wir heißen deine Kinder und folgen dir nicht mehr" },
    { book: "Iwdd!", number: 202, name: "Herr, wohin soll'n wir gehn" },
    { book: "Iwdd!", number: 203, name: "I have decided to follow Jesus" },
    { book: "Iwdd!", number: 203, name: "Ich bin entschieden, zu folgen Jesus" },
    { book: "Iwdd!", number: 204, name: "Lass mir das Ziel vor Augen bleiben (Bin ich versucht, auf mich zu schauen)" },
    { book: "Iwdd!", number: 205, name: "Erwählet euch heute, wem Ihr dienen wollt" },
    { book: "Iwdd!", number: 206, name: "Herr, wir sind zu dir gekommen, um in deinem Dienst zu stehn" },
    { book: "Iwdd!", number: 207, name: "Nimm mein Leben, Jesu, dir übergeb ich's für und für" },
    { book: "Iwdd!", number: 207, name: "Take my life, and let it be consecrated" },
    { book: "Iwdd!", number: 208, name: "Behalte mich in Deiner Pflege" },
    { book: "Iwdd!", number: 209, name: "Ich möcht ein Segen sein mehr, als ich war" },
    { book: "Iwdd!", number: 210, name: "Ich sage Ja zu Dir (Jesus Christus, mein Gott und mein Herr)" },
    { book: "Iwdd!", number: 211, name: "Wir leben und wirken und halten zusammen" },
    { book: "Iwdd!", number: 212, name: "Nimm Du mich ganz hin, o Gottessohn" },
    { book: "Iwdd!", number: 213, name: "Komm, geh mit mir in das Land" },
    { book: "Iwdd!", number: 214, name: "Praise the name of Jesus" },
    { book: "Iwdd!", number: 214, name: "Preist den Namen Jesus" },
    { book: "Iwdd!", number: 215, name: "Keinem von uns ist Gott fern (Ist dir Gott noch unbekannt)" },
    { book: "Iwdd!", number: 216, name: "Die Möwen, sie fliegen (Doch Gott hält für uns eine Wohnung bereit)" },
    { book: "Iwdd!", number: 217, name: "So wie ich bin, so muß es sein" },
    { book: "Iwdd!", number: 217, name: "Just as I am, without one plea" },
    { book: "Iwdd!", number: 218, name: "Hört den großen starken Namen: Jesus Christus, Gott und Herr" },
    { book: "Iwdd!", number: 219, name: "Kommt, singt mit uns das Lied der Freude" },
    { book: "Iwdd!", number: 220, name: "Such, wer da will, ein ander Ziel" },
    { book: "Iwdd!", number: 221, name: "Wer Jesus am Kreuze im Glauben erblickt" },
    { book: "Iwdd!", number: 222, name: "Would you be free from your burden of sin (There is power)" },
    { book: "Iwdd!", number: 222, name: "Möchtest du los sein vom Banne der Sünd (Es ist Kraft, Kraft, wunderbare Kraft)" },
    { book: "Iwdd!", number: 223, name: "Jesus Christus kennt dich, er allein weiß, was dir fehlt" },
    { book: "Iwdd!", number: 224, name: "Kehret um, kehret um, und ihr werdet leben" },
    { book: "Iwdd!", number: 225, name: "Fröhlich zieh ich meine Straße" },
    { book: "Iwdd!", number: 226, name: "O wende dich zu Jesu hin" },
    { book: "Iwdd!", number: 227, name: "Es ist niemand zu groß (Gott öffnet jedem die Tür)" },
    { book: "Iwdd!", number: 228, name: "Gestern, heute und für immer gleich" },
    { book: "Iwdd!", number: 229, name: "Hört, wen Jesus glücklich preist, Halleluja" },
    { book: "Iwdd!", number: 230, name: "Es geht ohne Gott in die Dunkelheit (Als die Welt noch jung war)" },
    { book: "Iwdd!", number: 231, name: "Dir fehlt wohl noch der Friede (O daß du könntest glauben)" },
    { book: "Iwdd!", number: 232, name: "Sag nicht nein. Gott ruft auch dich (Sieh, Er liebt dich)" },
    { book: "Iwdd!", number: 233, name: "Heute will dich Jesus fragen (Wag es mit Jesus)" },
    { book: "Iwdd!", number: 234, name: "Hast du den rechten Kurs für dein Leben (Wiedergeboren zu neuem Leben)" },
    { book: "Iwdd!", number: 235, name: "Siehe, Ich stehe vor der Tür und klopfe an" },
    { book: "Iwdd!", number: 236, name: "Gott lädt uns ein (Leben im Schatten)" },
    { book: "Iwdd!", number: 237, name: "Ich weiß einen Strom (O Seele, ich bitte dich: Komm)" },
    { book: "Iwdd!", number: 238, name: "Mag sein, du kannst es nicht verstehn" },
    { book: "Iwdd!", number: 239, name: "Noch dringt Jesu frohe Botschaft (Jesus Christus, Heiland und Erlöser)" },
    { book: "Iwdd!", number: 240, name: "Viele suchen dies und das (Steck den Kopf nicht in den Sand)" },
    { book: "Iwdd!", number: 241, name: "Sag, kennst du wohl den wunderbaren Namen (Name über alle Namen)" },
    { book: "Iwdd!", number: 242, name: "Gepriesen sei der Herr" },
    { book: "Iwdd!", number: 243, name: "Come with thy sins to the fountain (Haste thou away)" },
    { book: "Iwdd!", number: 243, name: "Komm doch zur Quelle des Lebens (Eile dahin)" },
    { book: "Iwdd!", number: 244, name: "Ich bin nicht irgendwer und nicht von ungefähr" },
    { book: "Iwdd!", number: 244, name: "Freuet euch in dieser Zeit" },
    { book: "Iwdd!", number: 245, name: "Gott hat uns geschaffen (Grenzenlose Freude)" },
    { book: "Iwdd!", number: 246, name: "Jesus kam, uns zu erlösen, preiset den Herrn" },
    { book: "Iwdd!", number: 247, name: "Gnade, die Jesus uns zugewandt (Gnade, Gnade)" },
    { book: "Iwdd!", number: 248, name: "Nichts habe ich, was nicht frei ich empfing (Einer, der Gottes Gnade fand)" },
    { book: "Iwdd!", number: 249, name: "Wie ein Fest nach langer Trauer (So ist Versöhnung)" },
    { book: "Iwdd!", number: 250, name: "On a hill far away (O that old rugged cross)" },
    { book: "Iwdd!", number: 250, name: "Dort auf Golgatha stand (Schätzen werd ich das alt rauhe Kreuz)" },
    { book: "Iwdd!", number: 251, name: "Vom Kreuz zeigt Jesus den Weg uns nach Haus (Vom Kreuz führt ein Weg nach Haus)" },
    { book: "Iwdd!", number: 252, name: "Christi Blut und Gerechtigkeit" },
    { book: "Iwdd!", number: 253, name: "Welch Glück ist's, erlöst zu sein (O preist Seiner Liebe Macht)" },
    { book: "Iwdd!", number: 254, name: "Mir ist Erbarmung widerfahren" },
    { book: "Iwdd!", number: 255, name: "Siehe, Ich habe dir geboten" },
    { book: "Iwdd!", number: 256, name: "Jesus, Dir nach, weil Du rufst" },
    { book: "Iwdd!", number: 257, name: "Ich habe nun den Grund gefunden" },
    { book: "Iwdd!", number: 258, name: "Jésus Christ, fils de Dieu (Merci notre Père)" },
    { book: "Iwdd!", number: 258, name: "There is a redeemer" },
    { book: "Iwdd!", number: 258, name: "Er ist der Erlöser" },
    { book: "Iwdd!", number: 259, name: "Die Gott lieben, werden sein wie die Sonne" },
    { book: "Iwdd!", number: 260, name: "Jesus lebet, Jesus siegt" },
    { book: "Iwdd!", number: 261, name: "Unser Glaube ist der Sieg" },
    { book: "Iwdd!", number: 262, name: "Bei Dir, dem Weinstock (Ich möchte bei dir bleiben)" },
    { book: "Iwdd!", number: 263, name: "Folge niemals dem Rat der gottlosen Leute (Dann wirst du sein wie ein Baum an der Quelle)" },
    { book: "Iwdd!", number: 264, name: "Ich lieb dich, Herr, keiner ist wie du" },
    { book: "Iwdd!", number: 265, name: "Viele Wege (Weise mir, Herr, Deinen Weg)" },
    { book: "Iwdd!", number: 266, name: "Blessed assurance, Jesus is mine (This is my story)" },
    { book: "Iwdd!", number: 266, name: "Seligstes Wissen: Jesus ist mein (Lasst mich's erzählen, Jesus zur Ehr)" },
    { book: "Iwdd!", number: 267, name: "Näher, mein Gott, zu dir" },
    { book: "Iwdd!", number: 267, name: "Nearer, my God, to Thee" },
    { book: "Iwdd!", number: 268, name: "Näher, noch näher" },
    { book: "Iwdd!", number: 268, name: "Nearer, still nearer" },
    { book: "Iwdd!", number: 269, name: "Nun gehören unsre Herzen" },
    { book: "Iwdd!", number: 270, name: "Meinen Jesus laß ich nicht" },
    { book: "Iwdd!", number: 271, name: "Jesu, geh voran" },
    { book: "Iwdd!", number: 272, name: "Ich brauch dich allezeit" },
    { book: "Iwdd!", number: 273, name: "Ich liebe Jesum alle Stund" },
    { book: "Iwdd!", number: 274, name: "Herr, füll mich neu" },
    { book: "Iwdd!", number: 275, name: "Prüfe mich, Herr, erforsche Du mein Herz" },
    { book: "Iwdd!", number: 276, name: "Du bist der Weg und die Wahrheit und das Leben" },
    { book: "Iwdd!", number: 277, name: "Bei dir, Jesu, will ich bleiben" },
    { book: "Iwdd!", number: 278, name: "Friede mit euch, Friede mit euch" },
    { book: "Iwdd!", number: 279, name: "Es ist gut, auf den Herrn zu vertrauen" },
    { book: "Iwdd!", number: 280, name: "Jesus, Du mein Leben, meines Herzens Streben" },
    { book: "Iwdd!", number: 281, name: "Immer auf Gott zu vertrauen" },
    { book: "Iwdd!", number: 282, name: "Geh, Abraham, geh" },
    { book: "Iwdd!", number: 283, name: "Mein Jesus, ich lieb dich" },
    { book: "Iwdd!", number: 283, name: "My Jesus, I love Thee, I know Thou art mine" },
    { book: "Iwdd!", number: 284, name: "Preis den Herrn, meine Seele" },
    { book: "Iwdd!", number: 285, name: "Jesus, wir sehen auf dich" },
    { book: "Iwdd!", number: 286, name: "Wachet auf, ruft uns die Stimme" },
    { book: "Iwdd!", number: 287, name: "Lass mich dein sein und bleiben" },
    { book: "Iwdd!", number: 288, name: "Zeichen der Liebe (Seid fröhlich in der Hoffnung)" },
    { book: "Iwdd!", number: 289, name: "Erforsche mich, Gott, und erkenne mein Herz" },
    { book: "Iwdd!", number: 290, name: "Herr, Du hast uns gerufen (Rede mit uns allezeit)" },
    { book: "Iwdd!", number: 291, name: "Und dennoch, wenns auch tobt und stürmt" },
    { book: "Iwdd!", number: 292, name: "Vom Himmel her kam ein Kind (Du, unser Gott, Du bist der Herr)" },
    { book: "Iwdd!", number: 292, name: "The Servant King (From heaven You came)" },
    { book: "Iwdd!", number: 293, name: "Vom Himmel kam Er zu uns (Du großer König Jesus Christ)" },
    { book: "Iwdd!", number: 294, name: "Jesus, mein Herr, wird immer mich lieben (Darum gehör ich Jesus)" },
    { book: "Iwdd!", number: 295, name: "The greatest thing in all my life" },
    { book: "Iwdd!", number: 295, name: "Das Höchste meines Lebens" },
    { book: "Iwdd!", number: 296, name: "Bind uns zusammen, Herr" },
    { book: "Iwdd!", number: 297, name: "Jesu Name nie verklinget" },
    { book: "Iwdd!", number: 298, name: "Jesu, meine Freude, meines Herzens Weide" },
    { book: "Iwdd!", number: 299, name: "Blicke nur auf Jesus, Seele, eil ihm zu" },
    { book: "Iwdd!", number: 300, name: "Jesus ist immer noch größer" },
    { book: "Iwdd!", number: 301, name: "Jesu, hilf siegen, du Fürste des Lebens" },
    { book: "Iwdd!", number: 302, name: "Brüder, noch gilt es zu retten (Auf Brüder, glauben heißt siegen)" },
    { book: "Iwdd!", number: 303, name: "Hast du eine Sorgenlast" },
    { book: "Iwdd!", number: 304, name: "Keiner wird zuschanden, welcher Gottes harrt" },
    { book: "Iwdd!", number: 305, name: "Fest und treu, wie Daniel war (Bleibe fest, wie Daniel)" },
    { book: "Iwdd!", number: 306, name: "Revive Thy work, o Lord" },
    { book: "Iwdd!", number: 306, name: "Beleb dein Werk, o Herr" },
    { book: "Iwdd!", number: 307, name: "Ja, ich glaub, Gott hört Gebet" },
    { book: "Iwdd!", number: 308, name: "Geduld ist euch vonnöten" },
    { book: "Iwdd!", number: 309, name: "Jesus, Heiland meiner Seele" },
    { book: "Iwdd!", number: 310, name: "Die Gnade sei mit allen" },
    { book: "Iwdd!", number: 311, name: "A mighty fortress is our God" },
    { book: "Iwdd!", number: 311, name: "Ein feste Burg ist unser Gott" },
    { book: "Iwdd!", number: 312, name: "Ich freue mich, ich freu mich" },
    { book: "Iwdd!", number: 313, name: "Dass Jesus siegt, bleibt ewig ausgemacht" },
    { book: "Iwdd!", number: 314, name: "Welch ein Freund ist unser Jesus" },
    { book: "Iwdd!", number: 314, name: "What a friend we have in Jesus" },
    { book: "Iwdd!", number: 315, name: "Von Freiheit will ich singen" },
    { book: "Iwdd!", number: 316, name: "Work, for the night is coming" },
    { book: "Iwdd!", number: 316, name: "Auf, denn die Nacht wird kommen" },
    { book: "Iwdd!", number: 317, name: "Wir sehen die verlorene Welt" },
    { book: "Iwdd!", number: 317, name: "The vision of a dying world" },
    { book: "Iwdd!", number: 318, name: "Die Sach ist dein, Herr Jesu Christ" },
    { book: "Iwdd!", number: 319, name: "Du bist der Weg, und Du führst zur Wahrheit" },
    { book: "Iwdd!", number: 320, name: "Hast du Jesu Ruf vernommen" },
    { book: "Iwdd!", number: 321, name: "Jesus, ich will gehn, sende mich" },
    { book: "Iwdd!", number: 322, name: "Wir schämen uns der Botschaft nicht" },
    { book: "Iwdd!", number: 323, name: "Jesus ist der schönste Nam" },
    { book: "Iwdd!", number: 324, name: "Jesus sucht Leute" },
    { book: "Iwdd!", number: 325, name: "Stimmt zu Gottes Ehren froh ein Loblied an" },
    { book: "Iwdd!", number: 326, name: "Jetzt ist die Zeit zu bauen" },
    { book: "Iwdd!", number: 327, name: "Vom Aufgang der Sonne" },
    { book: "Iwdd!", number: 328, name: "Siehe, Finsternis bedeckt die Erde" },
    { book: "Iwdd!", number: 329, name: "Wach auf, du Geist der ersten Zeugen" },
    { book: "Iwdd!", number: 330, name: "Herr, Du gibst uns Hoffnung, Du änderst unser Leben" },
    { book: "Iwdd!", number: 331, name: "Du gibst das Leben, das sich wirklich lohnt" },
    { book: "Iwdd!", number: 332, name: "Befiehl dem Herrn deine Wege (Kanon)" },
    { book: "Iwdd!", number: 333, name: "Jesus ist immer da, er ist dir heute nah" },
    { book: "Iwdd!", number: 334, name: "Die Güte Gottes preisen soll meine Freude sein" },
    { book: "Iwdd!", number: 335, name: "Sende dein Licht und deine Wahrheit" },
    { book: "Iwdd!", number: 336, name: "Meine Zeit steht in Deinen Händen" },
    { book: "Iwdd!", number: 337, name: "Rufe mich an in der Not (Kanon)" },
    { book: "Iwdd!", number: 338, name: "Sag ja zu Gottes Wegen, Gottes Wege sind immer gut" },
    { book: "Iwdd!", number: 339, name: "O Heiland, fülle meinen Tag (In keinem andern ist ja Heil)" },
    { book: "Iwdd!", number: 340, name: "Fröhlich, fröhlich ist das Volk" },
    { book: "Iwdd!", number: 341, name: "Herr, manche Tage sind für mich eine Last" },
    { book: "Iwdd!", number: 342, name: "Hell strahlt die Sonne" },
    { book: "Iwdd!", number: 343, name: "Ein neuer Tag beginnt, und ich freu mich (Warst die ganze Nacht mir nah)" },
    { book: "Iwdd!", number: 344, name: "Dies ist der Tag, dies ist der Tag, den der Herr gemacht" },
    { book: "Iwdd!", number: 345, name: "Danke für diesen guten Morgen" },
    { book: "Iwdd!", number: 346, name: "Die güldne Sonne" },
    { book: "Iwdd!", number: 347, name: "Lass mich Dir singen, Herr" },
    { book: "Iwdd!", number: 348, name: "Er weckt mich alle Morgen" },
    { book: "Iwdd!", number: 349, name: "Die Sonne sinkt, die Gnade nicht" },
    { book: "Iwdd!", number: 350, name: "Herr, bleib bei mir, der Abend bricht herein (Bleib bei mir, Herr!)" },
    { book: "Iwdd!", number: 351, name: "Mein schönste Zier und Kleinod" },
    { book: "Iwdd!", number: 352, name: "Nun wollen wir singen das Abendlied" },
    { book: "Iwdd!", number: 353, name: "Diesen Tag, Herr, leg ich zurück in Deine Hände" },
    { book: "Iwdd!", number: 354, name: "Es wird Abend, schlafen geht die Welt" },
    { book: "Iwdd!", number: 355, name: "Abend ward, bald kommt die Nacht" },
    { book: "Iwdd!", number: 356, name: "Bleibe bei uns, denn es wird Nacht (Mutlos und traurig)" },
    { book: "Iwdd!", number: 357, name: "Toben auch Stürme" },
    { book: "Iwdd!", number: 358, name: "When all my labors and trials are over (O that will be glory for me)" },
    { book: "Iwdd!", number: 358, name: "Wenn nach der Erde Leid, Arbeit und Pein (Das wird allein Herrlichkeit sein)" },
    { book: "Iwdd!", number: 359, name: "Bald schon kann es sein, dass wir Gott als König sehn" },
    { book: "Iwdd!", number: 360, name: "Keiner weiß, wann" },
    { book: "Iwdd!", number: 361, name: "Wir haben eine Hoffnung (Jesus kommt wieder)" },
    { book: "Iwdd!", number: 362, name: "Du sollst nicht müde werden (Wir werden sein wie die Träumenden)" },
    { book: "Iwdd!", number: 363, name: "Wir warten dein, o Gottessohn" },
    { book: "Iwdd!", number: 364, name: "Dann wird es kein Leid mehr geben (Gott wird sein alles und in allen)" },
    { book: "Iwdd!", number: 365, name: "Soon and very soon" },
    { book: "Iwdd!", number: 365, name: "Mine eyes have seen the glory (Glory! glory! hallelujah)" },
    { book: "Iwdd!", number: 365, name: "Viele Augen warten heute (Ehre, Ehre Seinem Namen)" },
    { book: "Iwdd!", number: 366, name: "Lobpreiset unsern Gott (Freuet euch, ich komm)" },
    { book: "Iwdd!", number: 367, name: "Lass mich an dich glauben, wie Abraham es tat" },
    { book: "Iwdd!", number: 368, name: "Du bist mein Ziel, mein Gott" },
    { book: "Iwdd!", number: 369, name: "Mein Glaube fest sich bauen kann (Wer diesem Felsen fest vertraut)" },
    { book: "Iwdd!", number: 369, name: "My hope is built on nothing less (On Christ, the solid rock, I stand)" },
    { book: "Iwdd!", number: 370, name: "Solang mein Jesus lebt (So lang mein Jesus lebt)" },
    { book: "Iwdd!", number: 371, name: "Wir haben einen Felsen, der unbeweglich steht" },
    { book: "Iwdd!", number: 372, name: "Stern, auf den ich schaue" },
    { book: "Iwdd!", number: 373, name: "Denn ich bin gewiss, dass weder Tod noch Leben" },
    { book: "Iwdd!", number: 374, name: "Im Kreuz ist unsre Kraft verborgen (Denn die da harren auf den Herrn)" },
    { book: "Iwdd!", number: 375, name: "Ich steh in meines Herren Hand" },
    { book: "Iwdd!", number: 376, name: "So nimm denn meine Hände" },
    { book: "Iwdd!", number: 377, name: "Aber der Herr ist immer noch größer (Wellen der Angst)" },
    { book: "Iwdd!", number: 378, name: "Herr, weil mich festhält deine starke Hand" },
    { book: "Iwdd!", number: 379, name: "Im Glauben und Vertrauen" },
    { book: "Iwdd!", number: 380, name: "Wie tief kann ich fallen (Nie tiefer als in Gottes Hand)" },
    { book: "Iwdd!", number: 381, name: "Wer Gott folgt, riskiert seine Träume" },
    { book: "Iwdd!", number: 382, name: "Glauben heißt vertrauen Gottes Vaterhut" },
    { book: "Iwdd!", number: 383, name: "Wohl denen, die da wandeln" },
    { book: "Iwdd!", number: 384, name: "Es sind der Gaben auf Erden viel" },
    { book: "Iwdd!", number: 385, name: "Jesus nur alleine sei mein Losungswort" },
    { book: "Iwdd!", number: 386, name: "Freu dich an der Sonne (Ich habe Freude, ja Freude, die bis morgen bleibt)" },
    { book: "Iwdd!", number: 387, name: "Suchet den Herrn, so werdet ihr leben (Kanon)" },
    { book: "Iwdd!", number: 388, name: "In dir ist Freude" },
    { book: "Iwdd!", number: 389, name: "Wir bekümmern uns nicht, denn die Freude am Herrn" },
    { book: "Iwdd!", number: 390, name: "Richte unsre Füße auf den Weg des Friedens (Siehe, ich breite aus den Frieden)" },
    { book: "Iwdd!", number: 391, name: "Wie das Licht nach der Nacht" },
    { book: "Iwdd!", number: 392, name: "Weiß ich den Weg auch nicht" },
    { book: "Iwdd!", number: 393, name: "Dank sei dir, ja, Dank sei dir" },
    { book: "Iwdd!", number: 394, name: "Ich blicke voll Beugung und Staunen" },
    { book: "Iwdd!", number: 395, name: "Dankt dem Herrn mit frohem Mut" },
    { book: "Iwdd!", number: 396, name: "Du hast mein Leben so reich gemacht" },
    { book: "Iwdd!", number: 397, name: "When peace like a river (It is well with my soul)" },
    { book: "Iwdd!", number: 397, name: "Wenn Friede mit Gott meine Seele durchdringt (Mir ist wohl in dem Herrn)" },
    { book: "Iwdd!", number: 398, name: "Like a river, glorious (Stayed upon Jehovah)" },
    { book: "Iwdd!", number: 398, name: "Wie ein Strom von oben" },
    { book: "Iwdd!", number: 399, name: "Ich will den Namen des Herrn preisen" },
    { book: "Iwdd!", number: 400, name: "Nun aufwärts froh den Blick gewandt" },
    { book: "Iwdd!", number: 401, name: "Father, make us one" },
    { book: "Iwdd!", number: 401, name: "Vater, mach uns eins, Vater, mach uns eins, dass die Welt erkennt" },
    { book: "Iwdd!", number: 402, name: "O Herr, ich habe lieb die Stätte Deines Hauses" },
    { book: "Iwdd!", number: 403, name: "Du hast uns als Gemeinde in Deinen Dienst gestellt" },
    { book: "Iwdd!", number: 404, name: "The church's one foundation" },
    { book: "Iwdd!", number: 404, name: "Die Kirche steht gegründet allein auf Jesum Christ" },
    { book: "Iwdd!", number: 405, name: "Selig sind, die Frieden stiften" },
    { book: "Iwdd!", number: 406, name: "Wenn Gott will und wir leben" },
    { book: "Iwdd!", number: 407, name: "Gut, dass wir einander haben" },
    { book: "Iwdd!", number: 408, name: "Ein jeder trage die Last des andern" },
    { book: "Iwdd!", number: 409, name: "Lasset uns Ihn lieben" },
    { book: "Iwdd!", number: 410, name: "Er hat mich so geliebt" },
    { book: "Iwdd!", number: 410, name: "Gott baut Sein Haus, Stein auf Stein" },
    { book: "Iwdd!", number: 411, name: "Herz und Herz vereint zusammen" },
    { book: "Iwdd!", number: 412, name: "Ich will einziehn in sein Tor" },
    { book: "Iwdd!", number: 412, name: "I will enter His gates" },
    { book: "Iwdd!", number: 413, name: "Der Tempel (Jesus will uns bau'n zu einem Tempel)" },
    { book: "Iwdd!", number: 414, name: "Es pilgert durch die Lande" },
    { book: "Iwdd!", number: 415, name: "Ich will loben Jesus, solange ich lebe" },
    { book: "Iwdd!", number: 416, name: "Herr, wir stehen Hand in Hand" },
    { book: "Iwdd!", number: 417, name: "Überwunden durch das Blut (Triumphierend brach das Lamm Satans Macht entzwei)" },
    { book: "Iwdd!", number: 418, name: "Lass du mich stille werden, mein Herr und Gott" },
    { book: "Iwdd!", number: 419, name: "Erforsche mich, Jesu, mein Licht" },
    { book: "Iwdd!", number: 420, name: "Nicht der Anfang, nur das Ende" },
    { book: "Iwdd!", number: 421, name: "Der Herr ist treu (Kanon)" },
    { book: "Iwdd!", number: 422, name: "Herr, halte mich nah bei Dir jeden Tag (Herr, mach aus mir ein Gefäß)" },
    { book: "Iwdd!", number: 423, name: "Unser Herr sagt uns in Seinem Wort (Wenn wir fest mit Ihm verbunden sind)" },
    { book: "Iwdd!", number: 424, name: "Du allein bist Gott. Dir gehört die Macht" },
    { book: "Iwdd!", number: 425, name: "Dass dein Wort in meinem Herzen" },
    { book: "Iwdd!", number: 426, name: "Nicht mehr mein Ich, sondern Christus lebt in mir" },
    { book: "Iwdd!", number: 427, name: "Gib mir Liebe ins Herz, lass mich leuchten (Sing Hosianna)" },
    { book: "Iwdd!", number: 428, name: "Shine, Jesus, shine (Lord, the light of Your love)" },
    { book: "Iwdd!", number: 428, name: "Herr, das Licht Deiner Liebe leuchtet auf (Jesus, dein Licht)" },
    { book: "Iwdd!", number: 429, name: "Heilge Liebe, unaussprechlich" },
    { book: "Iwdd!", number: 430, name: "O Gott, schaffe in mir ein reines Herz" },
    { book: "Iwdd!", number: 431, name: "Brich mir das Lebensbrot, Du großer Herr" },
    { book: "Iwdd!", number: 432, name: "Lehre mich glauben, Herr, lehre mich flehn" },
    { book: "Iwdd!", number: 433, name: "In's Wasser fällt ein Stein (Ins Wasser fällt ein Stein)" },
    { book: "Iwdd!", number: 433, name: "Es fällt uns oft so schwer, mit Menschen auszukommen" },
    { book: "Iwdd!", number: 434, name: "Ich will den Herrn loben allezeit (Kanon)" },
    { book: "Iwdd!", number: 435, name: "Called unto holiness (Holiness unto the Lord)" },
    { book: "Iwdd!", number: 435, name: "Heilig dem Herrn!, das heißt: Kirche des Herrn (Heilig dem Herrn! ist die Losung)" },
    { book: "Iwdd!", number: 436, name: "Wer auf Gott vertraut (Denn Er hat Seinen Engeln befohlen)" },
    { book: "Iwdd!", number: 437, name: "Sicher in Jesu Armen, sicher an Seiner Brust" },
    { book: "Iwdd!", number: 438, name: "Du bist mein Zufluchtsort, Du bist mein Schirm, mein Gott" },
    { book: "Iwdd!", number: 439, name: "Gott will's machen, dass die Sachen" },
    { book: "Iwdd!", number: 440, name: "Der Herr ist gut, in dessen Dienst wir stehn" },
    { book: "Iwdd!", number: 441, name: "Lasset uns laufen durch Geduld" },
    { book: "Iwdd!", number: 442, name: "Du bist unsre Zuversicht. Du bist unsre Stärke" },
    { book: "Iwdd!", number: 443, name: "Gott wird dich tragen, drum sei nicht verzagt" },
    { book: "Iwdd!", number: 444, name: "Lasst uns miteinander (Kanon)" },
    { book: "Iwdd!", number: 445, name: "Ohne Weg, ohne Licht, ohne Hilfe (Seine Güte und Gnade und Seine große Treu)" },
    { book: "Iwdd!", number: 445, name: "A pilgrim was I (Surely goodness and mercy)" },
    { book: "Iwdd!", number: 446, name: "Zünde an dein Feuer" },
    { book: "Iwdd!", number: 447, name: "Befiehl du deine Wege" },
    { book: "Iwdd!", number: 448, name: "Himmel und Erde werden vergehn" },
    { book: "Iwdd!", number: 449, name: "Kommt doch her zu Mir" },
    { book: "Iwdd!", number: 450, name: "Amen! Amen! lauter Amen" },
    { book: "Iwdd!", number: 451, name: "Helfer der Schwachen, kehre Dich zu mir" },
    { book: "Iwdd!", number: 452, name: "Jesus, die Sonne, das strahlende Licht" },
    { book: "Iwdd!", number: 453, name: "Du bist Immanuel: Mit uns ist Gott" },
    { book: "Iwdd!", number: 454, name: "Weil Gott die Welt so unendlich liebt" },
    { book: "Iwdd!", number: 455, name: "Harre, meine Seele, harre des Herrn" },
    { book: "Iwdd!", number: 456, name: "Nimmst Du mich noch einmal an?" },
    { book: "Iwdd!", number: 457, name: "Alles, was atmet, alles, was lebt (Der See, der den Himmel spiegelt)" },
    { book: "Iwdd!", number: 458, name: "Herr, ich sehe deine Welt" },
    { book: "Iwdd!", number: 459, name: "Geh aus, mein Herz, und suche Freud" },
    { book: "Iwdd!", number: 460, name: "Wie groß ist mein Gott, kein andrer wie er" },
    { book: "Iwdd!", number: 461, name: "Ja, das ist Freude" },
    { book: "Iwdd!", number: 462, name: "Es gibt jemand, der deine Lasten kennt" },
    { book: "Iwdd!", number: 463, name: "Wenn ich bedenke, was der Herr getan" },

    // Loben (b/B)
    { book: 'Loben', number: 1, name: 'Lobe den Herrn, meine Seele (I)' },
    { book: 'Loben', number: 2, name: 'Lobe den Herrn, meine Seele (II)' },
    { book: 'Loben', number: 3, name: 'Herr, dein Name sei erhöht' },
    { book: 'Loben', number: 3, name: 'Lord, I lift Your name on high' },
    { book: 'Loben', number: 4, name: 'Abba, Father' },
    { book: 'Loben', number: 4, name: 'Abba, Vater' },
    { book: 'Loben', number: 5, name: 'Wir sehen nicht vorbei' },
    { book: 'Loben', number: 6, name: 'Bin überreich beschenkt' },
    { book: 'Loben', number: 6, name: 'Reich, du machst mein Leben wirklich reich' },
    { book: 'Loben', number: 7, name: 'All die Fülle ist in dir' },
    { book: 'Loben', number: 7, name: 'Dank sei dir' },
    { book: 'Loben', number: 8, name: 'All heav’n declares' },
    { book: 'Loben', number: 8, name: 'Der Himmel zeugt' },
    { book: 'Loben', number: 9, name: 'Denn er hat seinen Engeln befohlen' },
    { book: 'Loben', number: 9, name: 'Wer auf Gott vertraut' },
    { book: 'Loben', number: 10, name: 'Aber der Herr ist immer noch größer' },
    { book: 'Loben', number: 11, name: 'Aber das ist meine Freude (Kanon)' },
    { book: 'Loben', number: 12, name: 'Wer Gott folgt, riskiert seine Träume' },
    { book: 'Loben', number: 13, name: 'Allein deine Gnade genügt' },
    { book: 'Loben', number: 14, name: 'Meine Zeit steht in deinen Händen' },
    { book: 'Loben', number: 15, name: 'Sende dein Licht (Kanon)' },
    { book: 'Loben', number: 16, name: 'Bei dir, dem Weinstock' },
    { book: 'Loben', number: 17, name: 'Danket dem Herren' },
    { book: 'Loben', number: 18, name: 'Bei dir ist die Quelle des Lebens (Kanon)' },
    { book: 'Loben', number: 19, name: 'Ein neuer Tag beginnt' },
    { book: 'Loben', number: 20, name: 'Geh unter der Gnade' },
    { book: 'Loben', number: 21, name: 'Alles will ich Jesus weihen' },
    { book: 'Loben', number: 22, name: 'Ich will den Herrn loben allezeit (Kanon)' },
    { book: 'Loben', number: 23, name: 'Hab auf Hoffnung gebaut' },
    { book: 'Loben', number: 24, name: 'Herr, du bist die Liebe' },
    { book: 'Loben', number: 25, name: 'Alle Wege, alle Worte' },
    { book: 'Loben', number: 26, name: 'Auf dem Hügel Golgatha' },
    { book: 'Loben', number: 27, name: 'I’ve been redeemed' },
    { book: 'Loben', number: 27, name: 'Ich bin erlöst' },
    { book: 'Loben', number: 28, name: 'My Lord is coming back' },
    { book: 'Loben', number: 29, name: 'Sie banden Jesu Hände' },
    { book: 'Loben', number: 30, name: 'Es war noch nie so dunkel' },
    { book: 'Loben', number: 30, name: 'Schuldlos schuldig' },
    { book: 'Loben', number: 31, name: 'Auch dieser Tag' },
    { book: 'Loben', number: 31, name: 'Morgenlied' },
    { book: 'Loben', number: 32, name: 'Seid fröhlich, ihr Christen' },
    { book: 'Loben', number: 33, name: 'Schritte in Gottes Spuren' },
    { book: 'Loben', number: 33, name: 'Weil bei Jesus unser Glaube' },
    { book: 'Loben', number: 34, name: 'Du musst nicht mehr einsam sein' },
    { book: 'Loben', number: 34, name: 'Gott gibt Mut zum Leben' },
    { book: 'Loben', number: 35, name: 'Hell strahlt die Sonne' },
    { book: 'Loben', number: 36, name: 'Herr, ich seh die Himmel' },
    { book: 'Loben', number: 37, name: 'Freuet euch, das Grab ist leer!' },
    { book: 'Loben', number: 38, name: 'Friede, Friede' },
    { book: 'Loben', number: 39, name: 'Auf deine Gnade, Herr, kommt es an' },
    { book: 'Loben', number: 40, name: 'Ich möchte leben' },
    { book: 'Loben', number: 41, name: 'Seid fröhlich in der Hoffnung' },
    { book: 'Loben', number: 41, name: 'Zeichen der Liebe' },
    { book: 'Loben', number: 42, name: 'Wenn die Last der Welt' },
    { book: 'Loben', number: 43, name: 'Sonne, Mond und Sterne' },
    { book: 'Loben', number: 44, name: 'Awesome God' },
    { book: 'Loben', number: 45, name: 'Alle dürfen Vater zu Gott sagen' },
    { book: 'Loben', number: 45, name: 'Den Frieden für euch' },
    { book: 'Loben', number: 46, name: 'Bald schon kann es sein' },
    { book: 'Loben', number: 47, name: 'Der Grund unsrer Dankbarkeit' },
    { book: 'Loben', number: 48, name: 'Singt ein Lied für Jesus' },
    { book: 'Loben', number: 49, name: 'Befiehl du deine Wege (2 Liedsätze)' },
    { book: 'Loben', number: 50, name: 'Vater, ich möchte dir danken' },
    { book: 'Loben', number: 51, name: 'Vergiss nicht zu danken' },
    { book: 'Loben', number: 52, name: 'Bist du bereit?' },
    { book: 'Loben', number: 53, name: 'Danke, Herr, du bist für mich da' },
    { book: 'Loben', number: 54, name: 'Bist du müde, Träumen nachzujagen?' },
    { book: 'Loben', number: 55, name: 'Danke, mein Vater, für alles' },
    { book: 'Loben', number: 56, name: 'Create in me a clean heart' },
    { book: 'Loben', number: 57, name: 'Ich danke meinem Gott' },
    { book: 'Loben', number: 58, name: 'Herr, wohin soll’n wir gehn?' },
    { book: 'Loben', number: 59, name: 'Dass dein Wort in meinem Herzen' },
    { book: 'Loben', number: 60, name: 'El-Shaddai' },
    { book: 'Loben', number: 61, name: 'Dass wir in dir bleiben' },
    { book: 'Loben', number: 62, name: 'Herr, segne uns und behüte uns (I)' },
    { book: 'Loben', number: 63, name: 'Jesus, leite mich mit deinen Augen' },
    { book: 'Loben', number: 64, name: 'Day by day' },
    { book: 'Loben', number: 65, name: 'Ich will heute schon schmecken' },
    { book: 'Loben', number: 65, name: 'Muss ich erst krank sein' },
    { book: 'Loben', number: 66, name: 'Nähme ich Flügel der Morgenröte' },
    { book: 'Loben', number: 67, name: 'Dein Wort ist ein Licht' },
    { book: 'Loben', number: 67, name: 'Thy word is a lamp' },
    { book: 'Loben', number: 68, name: 'Gott segne dich' },
    { book: 'Loben', number: 69, name: 'Dem, der die Liebe ist' },
    { book: 'Loben', number: 70, name: 'Weil nichts mich trennen kann' },
    { book: 'Loben', number: 71, name: 'Vater, ich komme jetzt zu dir' },
    { book: 'Loben', number: 72, name: 'Denn ich bin gewiss' },
    { book: 'Loben', number: 73, name: 'Sieh, hier bin ich, mein König' },
    { book: 'Loben', number: 74, name: 'Lobe den Herrn! Sing ihm dein Lied!' },
    { book: 'Loben', number: 75, name: 'Das Ja der Liebe' },
    { book: 'Loben', number: 75, name: 'Im Anfang war das Wort' },
    { book: 'Loben', number: 76, name: 'Denn wer ist Gott' },
    { book: 'Loben', number: 77, name: 'Danket dem Herrn!' },
    { book: 'Loben', number: 78, name: 'Er ist der Herr, der dich lehrt' },
    { book: 'Loben', number: 79, name: 'Wie oft' },
    { book: 'Loben', number: 80, name: 'Am Ende kein Ausweg' },
    { book: 'Loben', number: 80, name: 'So ist Gott, er hört Gebet' },
    { book: 'Loben', number: 81, name: 'Der Herr ist mein Licht' },
    { book: 'Loben', number: 82, name: 'Seid nicht bekümmert' },
    { book: 'Loben', number: 83, name: 'Sei stark in dem Herrn' },
    { book: 'Loben', number: 84, name: 'Der Tag vergeht' },
    { book: 'Loben', number: 85, name: 'Die Gott lieben' },
    { book: 'Loben', number: 86, name: 'Love the Lord (Kanon)' },
    { book: 'Loben', number: 87, name: 'Diesen Tag, Herr' },
    { book: 'Loben', number: 88, name: 'Du bist mein Ziel' },
    { book: 'Loben', number: 89, name: 'Folgen' },
    { book: 'Loben', number: 90, name: 'Gott zeigt mir den Weg' },
    { book: 'Loben', number: 91, name: 'Dir, Herr, will ich danken' },
    { book: 'Loben', number: 92, name: 'Eines Tages hörte ich' },
    { book: 'Loben', number: 93, name: 'Gott, der Herr, ist unsre Zuversicht' },
    { book: 'Loben', number: 94, name: 'Du bist der Weg' },
    { book: 'Loben', number: 95, name: 'Du bist mein Zufluchtsort, du bist mein Schirm' },
    { book: 'Loben', number: 96, name: 'Du bist mein Zufluchtsort, ich berge mich (Kanon)' },
    { book: 'Loben', number: 97, name: 'Ich bin entschieden zu folgen Jesus' },
    { book: 'Loben', number: 98, name: 'Ich hab ihn treu erfunden' },
    { book: 'Loben', number: 99, name: 'Jesus, wir sehen auf dich' },
    { book: 'Loben', number: 100, name: 'Niemand ist so treu und gut' },
    { book: 'Loben', number: 101, name: 'Du bist unsre Zuversicht' },
    { book: 'Loben', number: 102, name: 'Von ganzem Herzen will ich dir danken' },
    { book: 'Loben', number: 103, name: 'Jesus, deine Hände' },
    { book: 'Loben', number: 104, name: 'Leben aus der Quelle' },
    { book: 'Loben', number: 105, name: 'Niemand ist größer als du' },
    { book: 'Loben', number: 106, name: 'Du bist würdig' },
    { book: 'Loben', number: 107, name: 'Preist ihn, den Herrn der Herrlichkeit' },
    { book: 'Loben', number: 108, name: 'Wenn er kommt' },
    { book: 'Loben', number: 109, name: 'Vater, deine Liebe' },
    { book: 'Loben', number: 110, name: 'Wir bekümmern uns nicht' },
    { book: 'Loben', number: 111, name: 'Lobt den Herrn für seine große Güte' },
    { book: 'Loben', number: 112, name: 'Unser Mund, der ist voll Jubel' },
    { book: 'Loben', number: 113, name: 'Du gibst das Leben (2 Liedsätze)' },
    { book: 'Loben', number: 114, name: 'Alle Macht im Himmel und auf Erden' },
    { book: 'Loben', number: 114, name: 'Manchmal weiß ich nicht mehr' },
    { book: 'Loben', number: 115, name: 'Ein jeder trage' },
    { book: 'Loben', number: 116, name: 'Erstaunlich reich' },
    { book: 'Loben', number: 117, name: 'Gott wurde arm für uns' },
    { book: 'Loben', number: 118, name: 'Du, der du das Bild Gottes bist' },
    { book: 'Loben', number: 119, name: 'Einer durchbrach den Himmel' },
    { book: 'Loben', number: 120, name: 'Er ist der Erlöser' },
    { book: 'Loben', number: 120, name: 'There is a redeemer' },
    { book: 'Loben', number: 121, name: 'Freunde, wir sind nicht befreit' },
    { book: 'Loben', number: 122, name: 'Hard times' },
    { book: 'Loben', number: 122, name: 'Is the rain' },
    { book: 'Loben', number: 123, name: 'Heaven is a wonderful place' },
    { book: 'Loben', number: 124, name: 'Was willst du mehr?' },
    { book: 'Loben', number: 125, name: 'Für mich gingst du nach Golgatha' },
    { book: 'Loben', number: 126, name: 'Gib mir die richtigen Worte' },
    { book: 'Loben', number: 127, name: 'Gott ist Liebe (Kanon)' },
    { book: 'Loben', number: 128, name: 'Wohl dem, der nicht wandelt' },
    { book: 'Loben', number: 129, name: 'Wie er mich durchbringt' },
    { book: 'Loben', number: 130, name: 'Viele Wege gibt es auf dieser Welt' },
    { book: 'Loben', number: 131, name: 'How I love You' },
    { book: 'Loben', number: 131, name: 'You are the One' },
    { book: 'Loben', number: 132, name: 'Ich bin bei euch' },
    { book: 'Loben', number: 133, name: 'Gott ist mein Heil' },
    { book: 'Loben', number: 134, name: 'Jesus ist der Weg' },
    { book: 'Loben', number: 135, name: 'Wag den Sprung' },
    { book: 'Loben', number: 136, name: 'Gott kennt keine Lügen' },
    { book: 'Loben', number: 137, name: 'Zünde an dein Feuer' },
    { book: 'Loben', number: 138, name: 'Was wir so fest in Händen halten' },
    { book: 'Loben', number: 139, name: 'Gott, du bist mein Gott' },
    { book: 'Loben', number: 140, name: 'Gott, mein Herr, es ist mir ernst' },
    { book: 'Loben', number: 140, name: 'Ich will dir danken' },
    { book: 'Loben', number: 141, name: 'Sein starker Arm' },
    { book: 'Loben', number: 141, name: 'Wenn morgens in den Tag ich geh' },
    { book: 'Loben', number: 142, name: 'Ich will dich loben in der Stille' },
    { book: 'Loben', number: 143, name: 'Kommt, stimmt doch mit uns ein' },
    { book: 'Loben', number: 144, name: 'Lobt den Herren in seiner Herrlichkeit' },
    { book: 'Loben', number: 144, name: 'Wo ist ein Gott wie Du' },
    { book: 'Loben', number: 145, name: 'Das Gütesiegel Gottes' },
    { book: 'Loben', number: 145, name: 'Gottes Güte gibt Gelassenheit' },
    { book: 'Loben', number: 146, name: 'Nimm mein Leben, Jesus' },
    { book: 'Loben', number: 147, name: 'In deinem Haus' },
    { book: 'Loben', number: 148, name: 'Groß ist dein Name' },
    { book: 'Loben', number: 149, name: 'Halleluja! Lobet Gott' },
    { book: 'Loben', number: 150, name: 'Kommt, atmet auf' },
    { book: 'Loben', number: 151, name: 'Jesus, ich will gehn' },
    { book: 'Loben', number: 152, name: 'Groß und wunderbar ist der Name Jesus' },
    { book: 'Loben', number: 153, name: 'Lasst uns danken statt zu klagen' },
    { book: 'Loben', number: 154, name: 'Ich sitze oder stehe' },
    { book: 'Loben', number: 155, name: 'Immer auf Gott zu vertrauen' },
    { book: 'Loben', number: 156, name: 'Gut, dass wir einander haben' },
    { book: 'Loben', number: 157, name: 'Herr, du erforschst und du kennst mich' },
    { book: 'Loben', number: 158, name: 'Jesus, zu dir kann ich so kommen' },
    { book: 'Loben', number: 159, name: 'Komm in unser dürres Leben' },
    { book: 'Loben', number: 160, name: 'Herr, du gibst uns Hoffnung' },
    { book: 'Loben', number: 161, name: 'Lass mir das Ziel vor Augen bleiben' },
    { book: 'Loben', number: 162, name: 'Herr, halte mich nah bei dir' },
    { book: 'Loben', number: 163, name: 'Herr, mach mir deine Wege bekannt' },
    { book: 'Loben', number: 164, name: 'Manchmal frag ich mich' },
    { book: 'Loben', number: 165, name: 'Unverdient' },
    { book: 'Loben', number: 166, name: 'The servant king' },
    { book: 'Loben', number: 166, name: 'Vom Himmel her' },
    { book: 'Loben', number: 167, name: 'Herr, ich sehe deine Welt' },
    { book: 'Loben', number: 168, name: 'Bist zu uns wie ein Vater' },
    { book: 'Loben', number: 168, name: 'Vater, unser Vater' },
    { book: 'Loben', number: 169, name: 'What grace' },
    { book: 'Loben', number: 170, name: 'Wie der Töpfer nimmt den Ton' },
    { book: 'Loben', number: 171, name: 'Herr, in deinem Namen' },
    { book: 'Loben', number: 172, name: 'Father, I adore you' },
    { book: 'Loben', number: 172, name: 'Herr, mein ganzes Leben (Kanon)' },
    { book: 'Loben', number: 173, name: 'Die Hände, die sich falten' },
    { book: 'Loben', number: 173, name: 'Herr, lehr uns beten' },
    { book: 'Loben', number: 174, name: 'Ich will loben den Herrn allezeit (Kanon)' },
    { book: 'Loben', number: 175, name: 'Herr, wenn der Wunsch' },
    { book: 'Loben', number: 176, name: 'Jesus Christus ist der Sieger (Kanon)' },
    { book: 'Loben', number: 177, name: 'Ich singe immer wieder' },
    { book: 'Loben', number: 178, name: 'Ins Wasser fällt ein Stein' },
    { book: 'Loben', number: 179, name: 'Nur auf Gott' },
    { book: 'Loben', number: 180, name: 'Von Gottes Gnade singe ich' },
    { book: 'Loben', number: 181, name: 'Gemeinde bildest du' },
    { book: 'Loben', number: 182, name: 'In den Sternen Gottes Werk ich seh' },
    { book: 'Loben', number: 183, name: 'Wenn unser Glaube' },
    { book: 'Loben', number: 184, name: 'Deine Gnade sei mit uns' },
    { book: 'Loben', number: 185, name: 'Wenn du manchmal ganz alleine bist' },
    { book: 'Loben', number: 186, name: 'Beten' },
    { book: 'Loben', number: 186, name: 'In der Stille angekommen' },
    { book: 'Loben', number: 187, name: 'Vor der Tür' },
    { book: 'Loben', number: 187, name: 'Worauf’s ankommt' },
    { book: 'Loben', number: 188, name: 'Irgendeinen Platz' },
    { book: 'Loben', number: 189, name: 'Mein Jesus, mein Retter' },
    { book: 'Loben', number: 189, name: 'My Jesus, my saviour' },
    { book: 'Loben', number: 190, name: 'Trachtet zuerst nach Gottes Reich' },
    { book: 'Loben', number: 191, name: 'Du bist da' },
    { book: 'Loben', number: 191, name: 'Tagesanfang, hell und still' },
    { book: 'Loben', number: 192, name: 'Jeden Tag in meinem Leben' },
    { book: 'Loben', number: 193, name: 'Dass ich zu dir kommen darf' },
    { book: 'Loben', number: 194, name: 'Schöpfer aller Himmel' },
    { book: 'Loben', number: 195, name: 'Gestern war mir alles klar' },
    { book: 'Loben', number: 196, name: 'Komm heraus aus deiner Ecke' },
    { book: 'Loben', number: 196, name: 'Überall hat Gott seine Leute' },
    { book: 'Loben', number: 197, name: 'Jesus Christus starb für mich' },
    { book: 'Loben', number: 198, name: 'Zu deinem Thron, Herr' },
    { book: 'Loben', number: 199, name: 'Den ganzen langen Tag' },
    { book: 'Loben', number: 199, name: 'Nikodemus' },
    { book: 'Loben', number: 200, name: 'Jesus ist die Antwort' },
    { book: 'Loben', number: 201, name: 'Ganz für Gott' },
    { book: 'Loben', number: 202, name: 'Mehr lieben möcht ich dich' },
    { book: 'Loben', number: 203, name: 'Meine Seele ist stille in dir' },
    { book: 'Loben', number: 204, name: 'Immanuel' },
    { book: 'Loben', number: 204, name: 'Wir sahen ein Licht' },
    { book: 'Loben', number: 205, name: 'Da sind Worte voll Weisheit' },
    { book: 'Loben', number: 205, name: 'Worte zum Leben' },
    { book: 'Loben', number: 206, name: 'Jesus, dich will ich ehren' },
    { book: 'Loben', number: 207, name: 'Viele Menschen sagen' },
    { book: 'Loben', number: 208, name: 'Mag sein' },
    { book: 'Loben', number: 209, name: 'Wir wissen nicht den Tag' },
    { book: 'Loben', number: 210, name: 'Von guten Mächten' },
    { book: 'Loben', number: 211, name: 'Jesus, dir gehört mein Leben' },
    { book: 'Loben', number: 212, name: 'In dir ist Freude' },
    { book: 'Loben', number: 213, name: 'Keiner wird zuschanden' },
    { book: 'Loben', number: 214, name: 'Wer von der Liebe singt' },
    { book: 'Loben', number: 215, name: 'Jesus, dir nach, weil du rufst!' },
    { book: 'Loben', number: 216, name: 'Unser Herr sagt uns in seinem Wort' },
    { book: 'Loben', number: 217, name: 'Vor deinem Kreuz' },
    { book: 'Loben', number: 218, name: 'Weil Gott dein Vater ist' },
    { book: 'Loben', number: 219, name: 'Wenn Gott will und wenn wir leben' },
    { book: 'Loben', number: 220, name: 'Ein heller Morgen (Kanon)' },
    { book: 'Loben', number: 221, name: 'Du sollst nicht müde werden' },
    { book: 'Loben', number: 221, name: 'Wir werden sein wie die Träumenden' },
    { book: 'Loben', number: 222, name: 'Ein Leben, gegeben' },
    { book: 'Loben', number: 223, name: 'Ist dein Leben voller Schuld' },
    { book: 'Loben', number: 224, name: 'Wer das Wasser in der Wüste kennt' },
    { book: 'Loben', number: 225, name: 'Fürchte dich nicht, ich bin bei dir' },
    { book: 'Loben', number: 226, name: 'Es geht ohne Gott in die Dunkelheit' },
    { book: 'Loben', number: 227, name: 'Gott ist für uns' },
    { book: 'Loben', number: 228, name: 'Halt mich fest im Glauben' },
    { book: 'Loben', number: 229, name: 'Herr, hier ist mein Herz' },
    { book: 'Loben', number: 229, name: 'Lord, You have my heart' },
    { book: 'Loben', number: 230, name: 'Dass Jesus der Herr ist' },
    { book: 'Loben', number: 230, name: 'Nicht, dass wir schon alles wissen' },
    { book: 'Loben', number: 231, name: 'Alles, was atmet' },
    { book: 'Loben', number: 231, name: 'Der See, der den Himmel spiegelt' },
    { book: 'Loben', number: 232, name: 'Jesus, du bist gekrönt' },
    { book: 'Loben', number: 233, name: 'Wie groß ist mein Gott (Liederpotpourri)' },
    { book: 'Loben', number: 234, name: 'Lasst uns nicht länger schweigen' },
    { book: 'Loben', number: 234, name: 'Wo jeder recht hat' },
    { book: 'Loben', number: 235, name: 'O du Lamm Gottes' },
    { book: 'Loben', number: 236, name: 'Ich will streben nach dem Leben (2 Liedsätze)' },
    { book: 'Loben', number: 237, name: 'Lass die Sonne nicht' },
    { book: 'Loben', number: 238, name: 'Dich zu loben' },
    { book: 'Loben', number: 239, name: 'Auferstanden aus des Grabes Nacht' },
    { book: 'Loben', number: 240, name: 'Wie tief kann ich fallen' },
    { book: 'Loben', number: 241, name: 'Würdig das Lamm (Kanon)' },
    { book: 'Loben', number: 242, name: 'Herr, segne uns und behüte uns (II)' },
    { book: 'Loben', number: 243, name: 'Lobet den Herren, alle, die ihn ehren' },
    { book: 'Loben', number: 244, name: 'Bleibend ist deine Treu' },
    { book: 'Loben', number: 245, name: 'Du großer Gott' },
    { book: 'Loben', number: 246, name: 'Wir möchten Lieder singen' },
    { book: 'Loben', number: 247, name: 'Wir sind immer auf der Suche' },
    { book: 'Loben', number: 248, name: 'Woher weiß ich, was du willst' },
    { book: 'Loben', number: 249, name: 'Gott ist der Grund' },
    { book: 'Loben', number: 250, name: 'Was Gott sagt und was er tut' },
    { book: 'Loben', number: 250, name: 'Wenn auch die Berge weichen' },
    { book: 'Loben', number: 251, name: 'Wie hoch war die Schuld' },
    { book: 'Loben', number: 252, name: 'Bei dir bin ich angekommen' },
    { book: 'Loben', number: 253, name: 'Du bist da, Herr Jesus' },
    { book: 'Loben', number: 254, name: 'Herr Jesus Christus, Licht der Welt' },
    { book: 'Loben', number: 255, name: 'Diese Welt ist voller Fragen' },
    { book: 'Loben', number: 255, name: 'Du bist da, immer da' },
    { book: 'Loben', number: 256, name: 'Anker in der Zeit' },
    { book: 'Loben', number: 256, name: 'Es gibt bedingungslose Liebe' },
    { book: 'Loben', number: 257, name: 'Ich will dich anbeten' },
    { book: 'Loben', number: 258, name: 'I see the cross' },
    { book: 'Loben', number: 258, name: 'Ich seh das Kreuz' },
    { book: 'Loben', number: 259, name: 'You are my all in all' },
    { book: 'Loben', number: 259, name: 'You are my strength' },
    { book: 'Loben', number: 260, name: 'Ich verdanke dir so viel' },
    { book: 'Loben', number: 261, name: 'Du bist es, Herr, der mein Leben erhält' },
    { book: 'Loben', number: 261, name: 'Was geschieht, Herr' },
    { book: 'Loben', number: 262, name: 'Wie wir miteinander reden' },
    { book: 'Loben', number: 263, name: 'Neue Schritte wagen' },
    { book: 'Loben', number: 264, name: 'Die Majestät legtest du ab' },
    { book: 'Loben', number: 264, name: 'You laid aside your majesty' },
    { book: 'Loben', number: 265, name: 'Wirst du mich auch dann noch hören' },
    { book: 'Loben', number: 266, name: 'Du allein kennst meine Gedanken' },
    { book: 'Loben', number: 267, name: 'Seit nach Gottes Reich ich trachte' },
    { book: 'Loben', number: 268, name: 'Jesus Christus herrscht als König' },
    { book: 'Loben', number: 269, name: 'Out of the fullness' },
    { book: 'Loben', number: 270, name: 'Wer bist du' },
    { book: 'Loben', number: 271, name: 'Ich spiele Gitarre' },
    { book: 'Loben', number: 272, name: 'Ich bin bei dir' },
    { book: 'Loben', number: 273, name: 'Herr, du hast uns gerufen' },
    { book: 'Loben', number: 274, name: 'Folge niemals dem Rat' },
    { book: 'Loben', number: 275, name: 'Da, wo man ohne Hoffnung lebt' },
    { book: 'Loben', number: 276, name: 'Der Halm, den der Wind' },
    { book: 'Loben', number: 276, name: 'Hoffnung' },
    { book: 'Loben', number: 277, name: 'Gnade, die Jesus uns zugewandt' },
    { book: 'Loben', number: 278, name: 'Er ist der Weg, auf dem ich reise' },
    { book: 'Loben', number: 279, name: 'Denn ich weiß wohl' },
    { book: 'Loben', number: 279, name: 'Gedanken des Friedens' },
    { book: 'Loben', number: 280, name: 'Da kann man nur staunen' },
    { book: 'Loben', number: 280, name: 'Wie viel schöne Stunden' },
    { book: 'Loben', number: 281, name: 'Nimmst du mich noch einmal an?' },
    { book: 'Loben', number: 282, name: 'Gott macht nicht alle Hügel glatt' },
    { book: 'Loben', number: 283, name: 'Aus der Tiefe rufe ich, Herr, zu dir' },
    { book: 'Loben', number: 284, name: 'Bei dir, Jesus, will ich bleiben' },
    { book: 'Loben', number: 285, name: 'Die Gnade sei mit allen' },
    { book: 'Loben', number: 286, name: 'Herr, weil mich festhält' },
    { book: 'Loben', number: 287, name: 'Du meine Seele, singe' },
    { book: 'Loben', number: 288, name: 'Es ist niemand zu groß' },
    { book: 'Loben', number: 289, name: 'Herr, wir loben deine Gnade' },
    { book: 'Loben', number: 290, name: 'Herr, manche Tage' },
    { book: 'Loben', number: 291, name: 'Ich singe dir mit Herz und Mund' },
    { book: 'Loben', number: 292, name: 'Ich liebe nur Jesus' },
    { book: 'Loben', number: 293, name: 'Nun aufwärts froh den Blick gewandt' },
    { book: 'Loben', number: 294, name: 'Sag nicht nein' },
    { book: 'Loben', number: 295, name: 'Nun gehören unsre Herzen' },
    { book: 'Loben', number: 296, name: 'Weise mir, Herr, deinen Weg' },
    { book: 'Loben', number: 297, name: 'Abendlied' },
    { book: 'Loben', number: 297, name: 'Wenn der Tag zu Ende geht' },
    { book: 'Loben', number: 298, name: 'Wenn Friede mit Gott' },
    { book: 'Loben', number: 299, name: 'Wohin, wohin sollten wir gehen?' },
    { book: 'Loben', number: 300, name: 'Hör auf Gottes Wort' },
    { book: 'Loben', number: 300, name: 'Sag doch endlich ja' },
    { book: 'Loben', number: 301, name: 'Gott ist ein Gott, der große Dinge tut' },
    { book: 'Loben', number: 302, name: 'On the way out of town' },
    { book: 'Loben', number: 302, name: 'Victory over death' },
    { book: 'Loben', number: 303, name: 'Herr Jesus Christus, in dir ist Heil' },
    { book: 'Loben', number: 304, name: 'Herr, nun leg ich aus den Händen' },
    { book: 'Loben', number: 305, name: 'Du hast gesagt, du kommst zurück' },
    { book: 'Loben', number: 305, name: 'Keiner weiß wann' },
    { book: 'Loben', number: 306, name: 'Ich hörte Jesus, wie er sprach' },
    { book: 'Loben', number: 307, name: 'Leite uns, Herr' },
    { book: 'Loben', number: 308, name: 'Dankt für Gottes starke Hand' },
    { book: 'Loben', number: 308, name: 'Singt Dankeslieder' },
    { book: 'Loben', number: 309, name: 'In das Warten dieser Welt' },
    { book: 'Loben', number: 310, name: 'Gott macht es gut' },
    { book: 'Loben', number: 311, name: 'Du bist reich' },
    { book: 'Loben', number: 312, name: 'Danket, danket dem Herrn' },
    { book: 'Loben', number: 313, name: 'Josua-Lied' },
    { book: 'Loben', number: 313, name: 'Sei stark, erschrick nicht' },
    { book: 'Loben', number: 314, name: 'Herr, du bist mein Licht' },
    { book: 'Loben', number: 315, name: 'Gottes Segen sei mit dir' },
    { book: 'Loben', number: 316, name: 'Du bist die Tür' },
    { book: 'Loben', number: 316, name: 'Einen andern Grund' },
    { book: 'Loben', number: 317, name: 'In Christus, in Christus (Kanon)' },
    { book: 'Loben', number: 318, name: 'Dir, Herr, danken wir voll Freude' },
    { book: 'Loben', number: 319, name: 'Wie sag ich dir Dank' },
    { book: 'Loben', number: 320, name: 'Es leuchtet hell der Morgenstern' },
    { book: 'Loben', number: 321, name: 'Sein Erbarmen' },
    { book: 'Loben', number: 322, name: 'Auf, Seele, Gott zu loben' },
    { book: 'Loben', number: 323, name: 'Für Gottes Wort nehm ich mir Zeit' },
    { book: 'Loben', number: 323, name: 'Keiner, der durch Wüsten wandert' },
    { book: 'Loben', number: 324, name: 'Dein Wort ist meines Fußes Leuchte' },
    { book: 'Loben', number: 325, name: 'Ein junger Tag' },
    { book: 'Loben', number: 325, name: 'Morgenlied' },
    { book: 'Loben', number: 326, name: 'Wer liebt, ist gütig' },
    { book: 'Loben', number: 327, name: 'Ein neu’ Gebot' },
    { book: 'Loben', number: 328, name: 'Deine Hand, Herr, hält mich fest' },
    { book: 'Loben', number: 329, name: 'In meiner stillen Zeit' },
    { book: 'Loben', number: 330, name: 'Kommt und seht' },
    { book: 'Loben', number: 331, name: 'Schönster Herr Jesus' },
    { book: 'Loben', number: 332, name: 'Heute soll dir gehören' },
    { book: 'Loben', number: 333, name: 'Gottes Barmherzigkeit' },
    { book: 'Loben', number: 333, name: 'Herr, deine Güte' },
    { book: 'Loben', number: 334, name: 'Wirf dein Anliegen auf den Herrn' },
    { book: 'Loben', number: 335, name: 'Herr, du bist groß' },
    { book: 'Loben', number: 336, name: 'Lobe den Herrn, meine Seele (III)' },
    { book: 'Loben', number: 337, name: 'Wer unter dem Schirm' },
    { book: 'Loben', number: 338, name: 'Seht her, sein Knecht' },
    { book: 'Loben', number: 339, name: 'Zu Gottes Ehre' },
    { book: 'Loben', number: 340, name: 'Das wünsch ich dir' },
    { book: 'Loben', number: 340, name: 'Raum zum Träumen' },
    { book: 'Loben', number: 341, name: 'Mein Verlangen, dich zu ehren' },
    { book: 'Loben', number: 342, name: 'Den Gott uns gab' },
    { book: 'Loben', number: 343, name: 'I come to the cross' },
    { book: 'Loben', number: 343, name: 'Ich komme zum Kreuz' },
    { book: 'Loben', number: 344, name: 'Bald sehn wir dich' },
    { book: 'Loben', number: 345, name: 'Herr, deine Güte reicht so weit' },
    { book: 'Loben', number: 346, name: 'Siehe, ich bin bei dir' },
    { book: 'Loben', number: 347, name: 'So sehr hat Gott die Welt geliebet' },
    { book: 'Loben', number: 348, name: 'Herr Jesus, Dank sei dir' },
    { book: 'Loben', number: 349, name: 'Stern, auf den ich schaue' },
    { book: 'Loben', number: 350, name: 'Gemeinsam hat uns Gott diese Zeit geschenkt' },
    { book: 'Loben', number: 350, name: 'Getragen und geführt' },
    { book: 'Loben', number: 351, name: 'Jesus Christus starb für dich am Kreuz' },
    { book: 'Loben', number: 352, name: 'Der Herr ist mein Hirte' },
    { book: 'Loben', number: 353, name: 'Welch ein Freund ist unser Jesus' },
    { book: 'Loben', number: 354, name: 'O Gott, dir sei Ehre' },
    { book: 'Loben', number: 355, name: 'Herr, dein Erbarmen ist groß' },
    { book: 'Loben', number: 355, name: 'Herr, wie so groß ist deine Liebe am Kreuz' },
    { book: 'Loben', number: 356, name: 'Sei still, mein Herz' },
    { book: 'Loben', number: 357, name: 'O, die tiefe Liebe Jesu' },
    { book: 'Loben', number: 358, name: 'Ich will singen, dir, Herr Jesus!' },
    { book: 'Loben', number: 359, name: 'Ich geb mein Leben hin' },
    { book: 'Loben', number: 360, name: 'Preis und Anbetung' },
    { book: 'Loben', number: 361, name: 'Salz sein, Licht sein' },
    { book: 'Loben', number: 362, name: 'Lob, meine Seel, den Herrn' },
    { book: 'Loben', number: 363, name: 'Gegen den Strom!' },
    { book: 'Loben', number: 364, name: 'Ich weiß nicht' },
    { book: 'Loben', number: 365, name: 'Jesus lebt! Er hat gesiegt (2 Liedsätze)' },
];
