export interface Lied {
    book: string;
    number: number;
    name: string;
}

export const verzeichnis: Lied[] = [
    // Ich will dir danken!
    { book: "Iwdd!", number: 1, name: "Heilig, heilig, heilig, Gott" },
    { book: "Iwdd!", number: 2, name: "Heilig, heilig, heilig ist der Herr" },
    { book: "Iwdd!", number: 3, name: "Unser Vater in dem Himmel" },
    { book: "Iwdd!", number: 4, name: "Himmlischer Vater, wir beten dich an" },
    { book: "Iwdd!", number: 5, name: "Großer Gott, wir loben dich" },
    { book: "Iwdd!", number: 6, name: "Du großer Gott, wenn ich die Welt betrachte" },
    { book: "Iwdd!", number: 7, name: "Gott ist immer noch Gott" },
    { book: "Iwdd!", number: 8, name: "Vater, ich lieb dich" },
    { book: "Iwdd!", number: 9, name: "Elshaddai, El Elyonna Adonai" },
    { book: "Iwdd!", number: 10, name: "Herr, du mein Gott, du bist gut!" },
    { book: "Iwdd!", number: 11, name: "O Gott, dir sei Ehre, der Großes getan!" },
    // Loben
    { book: 'Loben', number: 1, name: 'Lobe den Herrn, meine Seele (I)' },
    { book: 'Loben', number: 2, name: 'Lobe den Herrn, meine Seele (II)' },
    { book: 'Loben', number: 3, name: 'Herr, dein Name sei erhöht' },
    { book: 'Loben', number: 3, name: 'Lord, I lift Your name on high' },
    { book: 'Loben', number: 4, name: 'Abba, Father' },
    { book: 'Loben', number: 4, name: 'Abba, Vater' },
    { book: 'Loben', number: 5, name: 'Wir sehen nicht vorbei' },
    { book: 'Loben', number: 6, name: 'Bin überreich beschenkt' },
    { book: 'Loben', number: 6, name: 'Reich, du machst mein Leben wirklich reich' },
    { book: 'Loben', number: 7, name: 'All die Fülle ist in dir' },
    { book: 'Loben', number: 7, name: 'Dank sei dir' },
    { book: 'Loben', number: 8, name: 'All heav’n declares' },
    { book: 'Loben', number: 8, name: 'Der Himmel zeugt' },
    { book: 'Loben', number: 9, name: 'Denn er hat seinen Engeln befohlen' },
    { book: 'Loben', number: 9, name: 'Wer auf Gott vertraut' },
    { book: 'Loben', number: 10, name: 'Aber der Herr ist immer noch größer' },
    { book: 'Loben', number: 11, name: 'Aber das ist meine Freude (Kanon)' },
    { book: 'Loben', number: 12, name: 'Wer Gott folgt, riskiert seine Träume' },
    { book: 'Loben', number: 13, name: 'Allein deine Gnade genügt' },
    { book: 'Loben', number: 14, name: 'Meine Zeit steht in deinen Händen' },
    { book: 'Loben', number: 15, name: 'Sende dein Licht (Kanon)' },
    { book: 'Loben', number: 16, name: 'Bei dir, dem Weinstock' },
    { book: 'Loben', number: 17, name: 'Danket dem Herren' },
    { book: 'Loben', number: 18, name: 'Bei dir ist die Quelle des Lebens (Kanon)' },
    { book: 'Loben', number: 19, name: 'Ein neuer Tag beginnt' },
    { book: 'Loben', number: 20, name: 'Geh unter der Gnade' },
    { book: 'Loben', number: 21, name: 'Alles will ich Jesus weihen' },
    { book: 'Loben', number: 22, name: 'Ich will den Herrn loben allezeit (Kanon)' },
    { book: 'Loben', number: 23, name: 'Hab auf Hoffnung gebaut' },
    { book: 'Loben', number: 24, name: 'Herr, du bist die Liebe' },
    { book: 'Loben', number: 25, name: 'Alle Wege, alle Worte' },
    { book: 'Loben', number: 26, name: 'Auf dem Hügel Golgatha' },
    { book: 'Loben', number: 27, name: 'I’ve been redeemed' },
    { book: 'Loben', number: 27, name: 'Ich bin erlöst' },
    { book: 'Loben', number: 28, name: 'My Lord is coming back' },
    { book: 'Loben', number: 29, name: 'Sie banden Jesu Hände' },
    { book: 'Loben', number: 30, name: 'Es war noch nie so dunkel' },
    { book: 'Loben', number: 30, name: 'Schuldlos schuldig' },
    { book: 'Loben', number: 31, name: 'Auch dieser Tag' },
    { book: 'Loben', number: 31, name: 'Morgenlied' },
    { book: 'Loben', number: 32, name: 'Seid fröhlich, ihr Christen' },
    { book: 'Loben', number: 33, name: 'Schritte in Gottes Spuren' },
    { book: 'Loben', number: 33, name: 'Weil bei Jesus unser Glaube' },
    { book: 'Loben', number: 34, name: 'Du musst nicht mehr einsam sein' },
    { book: 'Loben', number: 34, name: 'Gott gibt Mut zum Leben' },
    { book: 'Loben', number: 35, name: 'Hell strahlt die Sonne' },
    { book: 'Loben', number: 36, name: 'Herr, ich seh die Himmel' },
    { book: 'Loben', number: 37, name: 'Freuet euch, das Grab ist leer!' },
    { book: 'Loben', number: 38, name: 'Friede, Friede' },
    { book: 'Loben', number: 39, name: 'Auf deine Gnade, Herr, kommt es an' },
    { book: 'Loben', number: 40, name: 'Ich möchte leben' },
    { book: 'Loben', number: 41, name: 'Seid fröhlich in der Hoffnung' },
    { book: 'Loben', number: 41, name: 'Zeichen der Liebe' },
    { book: 'Loben', number: 42, name: 'Wenn die Last der Welt' },
    { book: 'Loben', number: 43, name: 'Sonne, Mond und Sterne' },
    { book: 'Loben', number: 44, name: 'Awesome God' },
    { book: 'Loben', number: 45, name: 'Alle dürfen Vater zu Gott sagen' },
    { book: 'Loben', number: 45, name: 'Den Frieden für euch' },
    { book: 'Loben', number: 46, name: 'Bald schon kann es sein' },
    { book: 'Loben', number: 47, name: 'Der Grund unsrer Dankbarkeit' },
    { book: 'Loben', number: 48, name: 'Singt ein Lied für Jesus' },
    { book: 'Loben', number: 49, name: 'Befiehl du deine Wege (2 Liedsätze)' },
    { book: 'Loben', number: 50, name: 'Vater, ich möchte dir danken' },
    { book: 'Loben', number: 51, name: 'Vergiss nicht zu danken' },
    { book: 'Loben', number: 52, name: 'Bist du bereit?' },
    { book: 'Loben', number: 53, name: 'Danke, Herr, du bist für mich da' },
    { book: 'Loben', number: 54, name: 'Bist du müde, Träumen nachzujagen?' },
    { book: 'Loben', number: 55, name: 'Danke, mein Vater, für alles' },
    { book: 'Loben', number: 56, name: 'Create in me a clean heart' },
    { book: 'Loben', number: 57, name: 'Ich danke meinem Gott' },
    { book: 'Loben', number: 58, name: 'Herr, wohin soll’n wir gehn?' },
    { book: 'Loben', number: 59, name: 'Dass dein Wort in meinem Herzen' },
    { book: 'Loben', number: 60, name: 'El-Shaddai' },
    { book: 'Loben', number: 61, name: 'Dass wir in dir bleiben' },
    { book: 'Loben', number: 62, name: 'Herr, segne uns und behüte uns (I)' },
    { book: 'Loben', number: 63, name: 'Jesus, leite mich mit deinen Augen' },
    { book: 'Loben', number: 64, name: 'Day by day' },
    { book: 'Loben', number: 65, name: 'Ich will heute schon schmecken' },
    { book: 'Loben', number: 65, name: 'Muss ich erst krank sein' },
    { book: 'Loben', number: 66, name: 'Nähme ich Flügel der Morgenröte' },
    { book: 'Loben', number: 67, name: 'Dein Wort ist ein Licht' },
    { book: 'Loben', number: 67, name: 'Thy word is a lamp' },
    { book: 'Loben', number: 68, name: 'Gott segne dich' },
    { book: 'Loben', number: 69, name: 'Dem, der die Liebe ist' },
    { book: 'Loben', number: 70, name: 'Weil nichts mich trennen kann' },
    { book: 'Loben', number: 71, name: 'Vater, ich komme jetzt zu dir' },
    { book: 'Loben', number: 72, name: 'Denn ich bin gewiss' },
    { book: 'Loben', number: 73, name: 'Sieh, hier bin ich, mein König' },
    { book: 'Loben', number: 74, name: 'Lobe den Herrn! Sing ihm dein Lied!' },
    { book: 'Loben', number: 75, name: 'Das Ja der Liebe' },
    { book: 'Loben', number: 75, name: 'Im Anfang war das Wort' },
    { book: 'Loben', number: 76, name: 'Denn wer ist Gott' },
    { book: 'Loben', number: 77, name: 'Danket dem Herrn!' },
    { book: 'Loben', number: 78, name: 'Er ist der Herr, der dich lehrt' },
    { book: 'Loben', number: 79, name: 'Wie oft' },
    { book: 'Loben', number: 80, name: 'Am Ende kein Ausweg' },
    { book: 'Loben', number: 80, name: 'So ist Gott, er hört Gebet' },
    { book: 'Loben', number: 81, name: 'Der Herr ist mein Licht' },
    { book: 'Loben', number: 82, name: 'Seid nicht bekümmert' },
    { book: 'Loben', number: 83, name: 'Sei stark in dem Herrn' },
    { book: 'Loben', number: 84, name: 'Der Tag vergeht' },
    { book: 'Loben', number: 85, name: 'Die Gott lieben' },
    { book: 'Loben', number: 86, name: 'Love the Lord (Kanon)' },
    { book: 'Loben', number: 87, name: 'Diesen Tag, Herr' },
    { book: 'Loben', number: 88, name: 'Du bist mein Ziel' },
    { book: 'Loben', number: 89, name: 'Folgen' },
    { book: 'Loben', number: 90, name: 'Gott zeigt mir den Weg' },
    { book: 'Loben', number: 91, name: 'Dir, Herr, will ich danken' },
    { book: 'Loben', number: 92, name: 'Eines Tages hörte ich' },
    { book: 'Loben', number: 93, name: 'Gott, der Herr, ist unsre Zuversicht' },
    { book: 'Loben', number: 94, name: 'Du bist der Weg' },
    { book: 'Loben', number: 95, name: 'Du bist mein Zufluchtsort, du bist mein Schirm' },
    { book: 'Loben', number: 96, name: 'Du bist mein Zufluchtsort, ich berge mich (Kanon)' },
    { book: 'Loben', number: 97, name: 'Ich bin entschieden zu folgen Jesus' },
    { book: 'Loben', number: 98, name: 'Ich hab ihn treu erfunden' },
    { book: 'Loben', number: 99, name: 'Jesus, wir sehen auf dich' },
    { book: 'Loben', number: 100, name: 'Niemand ist so treu und gut' },
    { book: 'Loben', number: 101, name: 'Du bist unsre Zuversicht' },
    { book: 'Loben', number: 102, name: 'Von ganzem Herzen will ich dir danken' },
    { book: 'Loben', number: 103, name: 'Jesus, deine Hände' },
    { book: 'Loben', number: 104, name: 'Leben aus der Quelle' },
    { book: 'Loben', number: 105, name: 'Niemand ist größer als du' },
    { book: 'Loben', number: 106, name: 'Du bist würdig' },
    { book: 'Loben', number: 107, name: 'Preist ihn, den Herrn der Herrlichkeit' },
    { book: 'Loben', number: 108, name: 'Wenn er kommt' },
    { book: 'Loben', number: 109, name: 'Vater, deine Liebe' },
    { book: 'Loben', number: 110, name: 'Wir bekümmern uns nicht' },
    { book: 'Loben', number: 111, name: 'Lobt den Herrn für seine große Güte' },
    { book: 'Loben', number: 112, name: 'Unser Mund, der ist voll Jubel' },
    { book: 'Loben', number: 113, name: 'Du gibst das Leben (2 Liedsätze)' },
    { book: 'Loben', number: 114, name: 'Alle Macht im Himmel und auf Erden' },
    { book: 'Loben', number: 114, name: 'Manchmal weiß ich nicht mehr' },
    { book: 'Loben', number: 115, name: 'Ein jeder trage' },
    { book: 'Loben', number: 116, name: 'Erstaunlich reich' },
    { book: 'Loben', number: 117, name: 'Gott wurde arm für uns' },
    { book: 'Loben', number: 118, name: 'Du, der du das Bild Gottes bist' },
    { book: 'Loben', number: 119, name: 'Einer durchbrach den Himmel' },
    { book: 'Loben', number: 120, name: 'Er ist der Erlöser' },
    { book: 'Loben', number: 120, name: 'There is a redeemer' },
    { book: 'Loben', number: 121, name: 'Freunde, wir sind nicht befreit' },
    { book: 'Loben', number: 122, name: 'Hard times' },
    { book: 'Loben', number: 122, name: 'Is the rain' },
    { book: 'Loben', number: 123, name: 'Heaven is a wonderful place' },
    { book: 'Loben', number: 124, name: 'Was willst du mehr?' },
    { book: 'Loben', number: 125, name: 'Für mich gingst du nach Golgatha' },
    { book: 'Loben', number: 126, name: 'Gib mir die richtigen Worte' },
    { book: 'Loben', number: 127, name: 'Gott ist Liebe (Kanon)' },
    { book: 'Loben', number: 128, name: 'Wohl dem, der nicht wandelt' },
    { book: 'Loben', number: 129, name: 'Wie er mich durchbringt' },
    { book: 'Loben', number: 130, name: 'Viele Wege gibt es auf dieser Welt' },
    { book: 'Loben', number: 131, name: 'How I love You' },
    { book: 'Loben', number: 131, name: 'You are the One' },
    { book: 'Loben', number: 132, name: 'Ich bin bei euch' },
    { book: 'Loben', number: 133, name: 'Gott ist mein Heil' },
    { book: 'Loben', number: 134, name: 'Jesus ist der Weg' },
    { book: 'Loben', number: 135, name: 'Wag den Sprung' },
    { book: 'Loben', number: 136, name: 'Gott kennt keine Lügen' },
    { book: 'Loben', number: 137, name: 'Zünde an dein Feuer' },
    { book: 'Loben', number: 138, name: 'Was wir so fest in Händen halten' },
    { book: 'Loben', number: 139, name: 'Gott, du bist mein Gott' },
    { book: 'Loben', number: 140, name: 'Gott, mein Herr, es ist mir ernst' },
    { book: 'Loben', number: 140, name: 'Ich will dir danken' },
    { book: 'Loben', number: 141, name: 'Sein starker Arm' },
    { book: 'Loben', number: 141, name: 'Wenn morgens in den Tag ich geh' },
    { book: 'Loben', number: 142, name: 'Ich will dich loben in der Stille' },
    { book: 'Loben', number: 143, name: 'Kommt, stimmt doch mit uns ein' },
    { book: 'Loben', number: 144, name: 'Lobt den Herren in seiner Herrlichkeit' },
    { book: 'Loben', number: 144, name: 'Wo ist ein Gott wie Du' },
    { book: 'Loben', number: 145, name: 'Das Gütesiegel Gottes' },
    { book: 'Loben', number: 145, name: 'Gottes Güte gibt Gelassenheit' },
    { book: 'Loben', number: 146, name: 'Nimm mein Leben, Jesus' },
    { book: 'Loben', number: 147, name: 'In deinem Haus' },
    { book: 'Loben', number: 148, name: 'Groß ist dein Name' },
    { book: 'Loben', number: 149, name: 'Halleluja! Lobet Gott' },
    { book: 'Loben', number: 150, name: 'Kommt, atmet auf' },
    { book: 'Loben', number: 151, name: 'Jesus, ich will gehn' },
    { book: 'Loben', number: 152, name: 'Groß und wunderbar ist der Name Jesus' },
    { book: 'Loben', number: 153, name: 'Lasst uns danken statt zu klagen' },
    { book: 'Loben', number: 154, name: 'Ich sitze oder stehe' },
    { book: 'Loben', number: 155, name: 'Immer auf Gott zu vertrauen' },
    { book: 'Loben', number: 156, name: 'Gut, dass wir einander haben' },
    { book: 'Loben', number: 157, name: 'Herr, du erforschst und du kennst mich' },
    { book: 'Loben', number: 158, name: 'Jesus, zu dir kann ich so kommen' },
    { book: 'Loben', number: 159, name: 'Komm in unser dürres Leben' },
    { book: 'Loben', number: 160, name: 'Herr, du gibst uns Hoffnung' },
    { book: 'Loben', number: 161, name: 'Lass mir das Ziel vor Augen bleiben' },
    { book: 'Loben', number: 162, name: 'Herr, halte mich nah bei dir' },
    { book: 'Loben', number: 163, name: 'Herr, mach mir deine Wege bekannt' },
    { book: 'Loben', number: 164, name: 'Manchmal frag ich mich' },
    { book: 'Loben', number: 165, name: 'Unverdient' },
    { book: 'Loben', number: 166, name: 'The servant king' },
    { book: 'Loben', number: 166, name: 'Vom Himmel her' },
    { book: 'Loben', number: 167, name: 'Herr, ich sehe deine Welt' },
    { book: 'Loben', number: 168, name: 'Bist zu uns wie ein Vater' },
    { book: 'Loben', number: 168, name: 'Vater, unser Vater' },
    { book: 'Loben', number: 169, name: 'What grace' },
    { book: 'Loben', number: 170, name: 'Wie der Töpfer nimmt den Ton' },
    { book: 'Loben', number: 171, name: 'Herr, in deinem Namen' },
    { book: 'Loben', number: 172, name: 'Father, I adore you' },
    { book: 'Loben', number: 172, name: 'Herr, mein ganzes Leben (Kanon)' },
    { book: 'Loben', number: 173, name: 'Die Hände, die sich falten' },
    { book: 'Loben', number: 173, name: 'Herr, lehr uns beten' },
    { book: 'Loben', number: 174, name: 'Ich will loben den Herrn allezeit (Kanon)' },
    { book: 'Loben', number: 175, name: 'Herr, wenn der Wunsch' },
    { book: 'Loben', number: 176, name: 'Jesus Christus ist der Sieger (Kanon)' },
    { book: 'Loben', number: 177, name: 'Ich singe immer wieder' },
    { book: 'Loben', number: 178, name: 'Ins Wasser fällt ein Stein' },
    { book: 'Loben', number: 179, name: 'Nur auf Gott' },
    { book: 'Loben', number: 180, name: 'Von Gottes Gnade singe ich' },
    { book: 'Loben', number: 181, name: 'Gemeinde bildest du' },
    { book: 'Loben', number: 182, name: 'In den Sternen Gottes Werk ich seh' },
    { book: 'Loben', number: 183, name: 'Wenn unser Glaube' },
    { book: 'Loben', number: 184, name: 'Deine Gnade sei mit uns' },
    { book: 'Loben', number: 185, name: 'Wenn du manchmal ganz alleine bist' },
    { book: 'Loben', number: 186, name: 'Beten' },
    { book: 'Loben', number: 186, name: 'In der Stille angekommen' },
    { book: 'Loben', number: 187, name: 'Vor der Tür' },
    { book: 'Loben', number: 187, name: 'Worauf’s ankommt' },
    { book: 'Loben', number: 188, name: 'Irgendeinen Platz' },
    { book: 'Loben', number: 189, name: 'Mein Jesus, mein Retter' },
    { book: 'Loben', number: 189, name: 'My Jesus, my saviour' },
    { book: 'Loben', number: 190, name: 'Trachtet zuerst nach Gottes Reich' },
    { book: 'Loben', number: 191, name: 'Du bist da' },
    { book: 'Loben', number: 191, name: 'Tagesanfang, hell und still' },
    { book: 'Loben', number: 192, name: 'Jeden Tag in meinem Leben' },
    { book: 'Loben', number: 193, name: 'Dass ich zu dir kommen darf' },
    { book: 'Loben', number: 194, name: 'Schöpfer aller Himmel' },
    { book: 'Loben', number: 195, name: 'Gestern war mir alles klar' },
    { book: 'Loben', number: 196, name: 'Komm heraus aus deiner Ecke' },
    { book: 'Loben', number: 196, name: 'Überall hat Gott seine Leute' },
    { book: 'Loben', number: 197, name: 'Jesus Christus starb für mich' },
    { book: 'Loben', number: 198, name: 'Zu deinem Thron, Herr' },
    { book: 'Loben', number: 199, name: 'Den ganzen langen Tag' },
    { book: 'Loben', number: 199, name: 'Nikodemus' },
    { book: 'Loben', number: 200, name: 'Jesus ist die Antwort' },
    { book: 'Loben', number: 201, name: 'Ganz für Gott' },
    { book: 'Loben', number: 202, name: 'Mehr lieben möcht ich dich' },
    { book: 'Loben', number: 203, name: 'Meine Seele ist stille in dir' },
    { book: 'Loben', number: 204, name: 'Immanuel' },
    { book: 'Loben', number: 204, name: 'Wir sahen ein Licht' },
    { book: 'Loben', number: 205, name: 'Da sind Worte voll Weisheit' },
    { book: 'Loben', number: 205, name: 'Worte zum Leben' },
    { book: 'Loben', number: 206, name: 'Jesus, dich will ich ehren' },
    { book: 'Loben', number: 207, name: 'Viele Menschen sagen' },
    { book: 'Loben', number: 208, name: 'Mag sein' },
    { book: 'Loben', number: 209, name: 'Wir wissen nicht den Tag' },
    { book: 'Loben', number: 210, name: 'Von guten Mächten' },
    { book: 'Loben', number: 211, name: 'Jesus, dir gehört mein Leben' },
    { book: 'Loben', number: 212, name: 'In dir ist Freude' },
    { book: 'Loben', number: 213, name: 'Keiner wird zuschanden' },
    { book: 'Loben', number: 214, name: 'Wer von der Liebe singt' },
    { book: 'Loben', number: 215, name: 'Jesus, dir nach, weil du rufst!' },
    { book: 'Loben', number: 216, name: 'Unser Herr sagt uns in seinem Wort' },
    { book: 'Loben', number: 217, name: 'Vor deinem Kreuz' },
    { book: 'Loben', number: 218, name: 'Weil Gott dein Vater ist' },
    { book: 'Loben', number: 219, name: 'Wenn Gott will und wenn wir leben' },
    { book: 'Loben', number: 220, name: 'Ein heller Morgen (Kanon)' },
    { book: 'Loben', number: 221, name: 'Du sollst nicht müde werden' },
    { book: 'Loben', number: 221, name: 'Wir werden sein wie die Träumenden' },
    { book: 'Loben', number: 222, name: 'Ein Leben, gegeben' },
    { book: 'Loben', number: 223, name: 'Ist dein Leben voller Schuld' },
    { book: 'Loben', number: 224, name: 'Wer das Wasser in der Wüste kennt' },
    { book: 'Loben', number: 225, name: 'Fürchte dich nicht, ich bin bei dir' },
    { book: 'Loben', number: 226, name: 'Es geht ohne Gott in die Dunkelheit' },
    { book: 'Loben', number: 227, name: 'Gott ist für uns' },
    { book: 'Loben', number: 228, name: 'Halt mich fest im Glauben' },
    { book: 'Loben', number: 229, name: 'Herr, hier ist mein Herz' },
    { book: 'Loben', number: 229, name: 'Lord, You have my heart' },
    { book: 'Loben', number: 230, name: 'Dass Jesus der Herr ist' },
    { book: 'Loben', number: 230, name: 'Nicht, dass wir schon alles wissen' },
    { book: 'Loben', number: 231, name: 'Alles, was atmet' },
    { book: 'Loben', number: 231, name: 'Der See, der den Himmel spiegelt' },
    { book: 'Loben', number: 232, name: 'Jesus, du bist gekrönt' },
    { book: 'Loben', number: 233, name: 'Wie groß ist mein Gott (Liederpotpourri)' },
    { book: 'Loben', number: 234, name: 'Lasst uns nicht länger schweigen' },
    { book: 'Loben', number: 234, name: 'Wo jeder recht hat' },
    { book: 'Loben', number: 235, name: 'O du Lamm Gottes' },
    { book: 'Loben', number: 236, name: 'Ich will streben nach dem Leben (2 Liedsätze)' },
    { book: 'Loben', number: 237, name: 'Lass die Sonne nicht' },
    { book: 'Loben', number: 238, name: 'Dich zu loben' },
    { book: 'Loben', number: 239, name: 'Auferstanden aus des Grabes Nacht' },
    { book: 'Loben', number: 240, name: 'Wie tief kann ich fallen' },
    { book: 'Loben', number: 241, name: 'Würdig das Lamm (Kanon)' },
    { book: 'Loben', number: 242, name: 'Herr, segne uns und behüte uns (II)' },
    { book: 'Loben', number: 243, name: 'Lobet den Herren, alle, die ihn ehren' },
    { book: 'Loben', number: 244, name: 'Bleibend ist deine Treu' },
    { book: 'Loben', number: 245, name: 'Du großer Gott' },
    { book: 'Loben', number: 246, name: 'Wir möchten Lieder singen' },
    { book: 'Loben', number: 247, name: 'Wir sind immer auf der Suche' },
    { book: 'Loben', number: 248, name: 'Woher weiß ich, was du willst' },
    { book: 'Loben', number: 249, name: 'Gott ist der Grund' },
    { book: 'Loben', number: 250, name: 'Was Gott sagt und was er tut' },
    { book: 'Loben', number: 250, name: 'Wenn auch die Berge weichen' },
    { book: 'Loben', number: 251, name: 'Wie hoch war die Schuld' },
    { book: 'Loben', number: 252, name: 'Bei dir bin ich angekommen' },
    { book: 'Loben', number: 253, name: 'Du bist da, Herr Jesus' },
    { book: 'Loben', number: 254, name: 'Herr Jesus Christus, Licht der Welt' },
    { book: 'Loben', number: 255, name: 'Diese Welt ist voller Fragen' },
    { book: 'Loben', number: 255, name: 'Du bist da, immer da' },
    { book: 'Loben', number: 256, name: 'Anker in der Zeit' },
    { book: 'Loben', number: 256, name: 'Es gibt bedingungslose Liebe' },
    { book: 'Loben', number: 257, name: 'Ich will dich anbeten' },
    { book: 'Loben', number: 258, name: 'I see the cross' },
    { book: 'Loben', number: 258, name: 'Ich seh das Kreuz' },
    { book: 'Loben', number: 259, name: 'You are my all in all' },
    { book: 'Loben', number: 259, name: 'You are my strength' },
    { book: 'Loben', number: 260, name: 'Ich verdanke dir so viel' },
    { book: 'Loben', number: 261, name: 'Du bist es, Herr, der mein Leben erhält' },
    { book: 'Loben', number: 261, name: 'Was geschieht, Herr' },
    { book: 'Loben', number: 262, name: 'Wie wir miteinander reden' },
    { book: 'Loben', number: 263, name: 'Neue Schritte wagen' },
    { book: 'Loben', number: 264, name: 'Die Majestät legtest du ab' },
    { book: 'Loben', number: 264, name: 'You laid aside your majesty' },
    { book: 'Loben', number: 265, name: 'Wirst du mich auch dann noch hören' },
    { book: 'Loben', number: 266, name: 'Du allein kennst meine Gedanken' },
    { book: 'Loben', number: 267, name: 'Seit nach Gottes Reich ich trachte' },
    { book: 'Loben', number: 268, name: 'Jesus Christus herrscht als König' },
    { book: 'Loben', number: 269, name: 'Out of the fullness' },
    { book: 'Loben', number: 270, name: 'Wer bist du' },
    { book: 'Loben', number: 271, name: 'Ich spiele Gitarre' },
    { book: 'Loben', number: 272, name: 'Ich bin bei dir' },
    { book: 'Loben', number: 273, name: 'Herr, du hast uns gerufen' },
    { book: 'Loben', number: 274, name: 'Folge niemals dem Rat' },
    { book: 'Loben', number: 275, name: 'Da, wo man ohne Hoffnung lebt' },
    { book: 'Loben', number: 276, name: 'Der Halm, den der Wind' },
    { book: 'Loben', number: 276, name: 'Hoffnung' },
    { book: 'Loben', number: 277, name: 'Gnade, die Jesus uns zugewandt' },
    { book: 'Loben', number: 278, name: 'Er ist der Weg, auf dem ich reise' },
    { book: 'Loben', number: 279, name: 'Denn ich weiß wohl' },
    { book: 'Loben', number: 279, name: 'Gedanken des Friedens' },
    { book: 'Loben', number: 280, name: 'Da kann man nur staunen' },
    { book: 'Loben', number: 280, name: 'Wie viel schöne Stunden' },
    { book: 'Loben', number: 281, name: 'Nimmst du mich noch einmal an?' },
    { book: 'Loben', number: 282, name: 'Gott macht nicht alle Hügel glatt' },
    { book: 'Loben', number: 283, name: 'Aus der Tiefe rufe ich, Herr, zu dir' },
    { book: 'Loben', number: 284, name: 'Bei dir, Jesus, will ich bleiben' },
    { book: 'Loben', number: 285, name: 'Die Gnade sei mit allen' },
    { book: 'Loben', number: 286, name: 'Herr, weil mich festhält' },
    { book: 'Loben', number: 287, name: 'Du meine Seele, singe' },
    { book: 'Loben', number: 288, name: 'Es ist niemand zu groß' },
    { book: 'Loben', number: 289, name: 'Herr, wir loben deine Gnade' },
    { book: 'Loben', number: 290, name: 'Herr, manche Tage' },
    { book: 'Loben', number: 291, name: 'Ich singe dir mit Herz und Mund' },
    { book: 'Loben', number: 292, name: 'Ich liebe nur Jesus' },
    { book: 'Loben', number: 293, name: 'Nun aufwärts froh den Blick gewandt' },
    { book: 'Loben', number: 294, name: 'Sag nicht nein' },
    { book: 'Loben', number: 295, name: 'Nun gehören unsre Herzen' },
    { book: 'Loben', number: 296, name: 'Weise mir, Herr, deinen Weg' },
    { book: 'Loben', number: 297, name: 'Abendlied' },
    { book: 'Loben', number: 297, name: 'Wenn der Tag zu Ende geht' },
    { book: 'Loben', number: 298, name: 'Wenn Friede mit Gott' },
    { book: 'Loben', number: 299, name: 'Wohin, wohin sollten wir gehen?' },
    { book: 'Loben', number: 300, name: 'Hör auf Gottes Wort' },
    { book: 'Loben', number: 300, name: 'Sag doch endlich ja' },
    { book: 'Loben', number: 301, name: 'Gott ist ein Gott, der große Dinge tut' },
    { book: 'Loben', number: 302, name: 'On the way out of town' },
    { book: 'Loben', number: 302, name: 'Victory over death' },
    { book: 'Loben', number: 303, name: 'Herr Jesus Christus, in dir ist Heil' },
    { book: 'Loben', number: 304, name: 'Herr, nun leg ich aus den Händen' },
    { book: 'Loben', number: 305, name: 'Du hast gesagt, du kommst zurück' },
    { book: 'Loben', number: 305, name: 'Keiner weiß wann' },
    { book: 'Loben', number: 306, name: 'Ich hörte Jesus, wie er sprach' },
    { book: 'Loben', number: 307, name: 'Leite uns, Herr' },
    { book: 'Loben', number: 308, name: 'Dankt für Gottes starke Hand' },
    { book: 'Loben', number: 308, name: 'Singt Dankeslieder' },
    { book: 'Loben', number: 309, name: 'In das Warten dieser Welt' },
    { book: 'Loben', number: 310, name: 'Gott macht es gut' },
    { book: 'Loben', number: 311, name: 'Du bist reich' },
    { book: 'Loben', number: 312, name: 'Danket, danket dem Herrn' },
    { book: 'Loben', number: 313, name: 'Josua-Lied' },
    { book: 'Loben', number: 313, name: 'Sei stark, erschrick nicht' },
    { book: 'Loben', number: 314, name: 'Herr, du bist mein Licht' },
    { book: 'Loben', number: 315, name: 'Gottes Segen sei mit dir' },
    { book: 'Loben', number: 316, name: 'Du bist die Tür' },
    { book: 'Loben', number: 316, name: 'Einen andern Grund' },
    { book: 'Loben', number: 317, name: 'In Christus, in Christus (Kanon)' },
    { book: 'Loben', number: 318, name: 'Dir, Herr, danken wir voll Freude' },
    { book: 'Loben', number: 319, name: 'Wie sag ich dir Dank' },
    { book: 'Loben', number: 320, name: 'Es leuchtet hell der Morgenstern' },
    { book: 'Loben', number: 321, name: 'Sein Erbarmen' },
    { book: 'Loben', number: 322, name: 'Auf, Seele, Gott zu loben' },
    { book: 'Loben', number: 323, name: 'Für Gottes Wort nehm ich mir Zeit' },
    { book: 'Loben', number: 323, name: 'Keiner, der durch Wüsten wandert' },
    { book: 'Loben', number: 324, name: 'Dein Wort ist meines Fußes Leuchte' },
    { book: 'Loben', number: 325, name: 'Ein junger Tag' },
    { book: 'Loben', number: 325, name: 'Morgenlied' },
    { book: 'Loben', number: 326, name: 'Wer liebt, ist gütig' },
    { book: 'Loben', number: 327, name: 'Ein neu’ Gebot' },
    { book: 'Loben', number: 328, name: 'Deine Hand, Herr, hält mich fest' },
    { book: 'Loben', number: 329, name: 'In meiner stillen Zeit' },
    { book: 'Loben', number: 330, name: 'Kommt und seht' },
    { book: 'Loben', number: 331, name: 'Schönster Herr Jesus' },
    { book: 'Loben', number: 332, name: 'Heute soll dir gehören' },
    { book: 'Loben', number: 333, name: 'Gottes Barmherzigkeit' },
    { book: 'Loben', number: 333, name: 'Herr, deine Güte' },
    { book: 'Loben', number: 334, name: 'Wirf dein Anliegen auf den Herrn' },
    { book: 'Loben', number: 335, name: 'Herr, du bist groß' },
    { book: 'Loben', number: 336, name: 'Lobe den Herrn, meine Seele (III)' },
    { book: 'Loben', number: 337, name: 'Wer unter dem Schirm' },
    { book: 'Loben', number: 338, name: 'Seht her, sein Knecht' },
    { book: 'Loben', number: 339, name: 'Zu Gottes Ehre' },
    { book: 'Loben', number: 340, name: 'Das wünsch ich dir' },
    { book: 'Loben', number: 340, name: 'Raum zum Träumen' },
    { book: 'Loben', number: 341, name: 'Mein Verlangen, dich zu ehren' },
    { book: 'Loben', number: 342, name: 'Den Gott uns gab' },
    { book: 'Loben', number: 343, name: 'I come to the cross' },
    { book: 'Loben', number: 343, name: 'Ich komme zum Kreuz' },
    { book: 'Loben', number: 344, name: 'Bald sehn wir dich' },
    { book: 'Loben', number: 345, name: 'Herr, deine Güte reicht so weit' },
    { book: 'Loben', number: 346, name: 'Siehe, ich bin bei dir' },
    { book: 'Loben', number: 347, name: 'So sehr hat Gott die Welt geliebet' },
    { book: 'Loben', number: 348, name: 'Herr Jesus, Dank sei dir' },
    { book: 'Loben', number: 349, name: 'Stern, auf den ich schaue' },
    { book: 'Loben', number: 350, name: 'Gemeinsam hat uns Gott diese Zeit geschenkt' },
    { book: 'Loben', number: 350, name: 'Getragen und geführt' },
    { book: 'Loben', number: 351, name: 'Jesus Christus starb für dich am Kreuz' },
    { book: 'Loben', number: 352, name: 'Der Herr ist mein Hirte' },
    { book: 'Loben', number: 353, name: 'Welch ein Freund ist unser Jesus' },
    { book: 'Loben', number: 354, name: 'O Gott, dir sei Ehre' },
    { book: 'Loben', number: 355, name: 'Herr, dein Erbarmen ist groß' },
    { book: 'Loben', number: 355, name: 'Herr, wie so groß ist deine Liebe am Kreuz' },
    { book: 'Loben', number: 356, name: 'Sei still, mein Herz' },
    { book: 'Loben', number: 357, name: 'O, die tiefe Liebe Jesu' },
    { book: 'Loben', number: 358, name: 'Ich will singen, dir, Herr Jesus!' },
    { book: 'Loben', number: 359, name: 'Ich geb mein Leben hin' },
    { book: 'Loben', number: 360, name: 'Preis und Anbetung' },
    { book: 'Loben', number: 361, name: 'Salz sein, Licht sein' },
    { book: 'Loben', number: 362, name: 'Lob, meine Seel, den Herrn' },
    { book: 'Loben', number: 363, name: 'Gegen den Strom!' },
    { book: 'Loben', number: 364, name: 'Ich weiß nicht' },
    { book: 'Loben', number: 365, name: 'Jesus lebt! Er hat gesiegt (2 Liedsätze)' },
];
