import { Song } from "./Contents"

export const Glorify: Song[] = [
  { number: 1, name: "Come praise and glorify" },
  { number: 2, name: "Kommt, preist und lobet unsern Gott" },
  { number: 3, name: "Du, der Höchste, El-Elyon" },
  { number: 4, name: "Allein zu deiner Ehre" },
  { number: 5, name: "Mein Verlangen, dich zu ehren" },
  { number: 6, name: "Glorious Day" },
  { number: 7, name: "Würdig das Lamm, das geopfert ist" },
  { number: 8, name: "Jesus, Fels der Zeiten" },
  { number: 9, name: "Jesus, dir nach, weil du rufst" },
  { number: 10, name: "Give thanks to the Lord, for He is good" },
  { number: 11, name: "Er ist der Erlöser" },
  { number: 12, name: "Er ist mein in Ewigkeit" },
  { number: 13, name: "Der Herr ist mein Licht" },
  { number: 14, name: "Du bist die Quelle" },
  { number: 15, name: "Amazing Grace" },
  { number: 16, name: "Lieber an der Tür" },
  { number: 17, name: "Tief verwurzelt" },
  { number: 18, name: "Was geschieht, Herr" },
  { number: 19, name: "Hard times" },
  { number: 20, name: "Lasst uns in Frieden beieinander wohnen" },
  { number: 21, name: "Allein deine Gnade genügt" },
  { number: 22, name: "Komm, und bete deinen König an" },
  { number: 23, name: "My Savior My God" },
  { number: 24, name: "Herr, du gibst uns Hoffnung" },
  { number: 25, name: "Alle Worte dieser Welt" },
  { number: 26, name: "Ich seh ein Meer, voll von Menschen" },
  { number: 27, name: "O Lord, You're beautiful" },
  { number: 28, name: "Wie der Töpfer nimmt den Ton" },
  { number: 29, name: "Das letzte Wort" },
  { number: 30, name: "Herr, halte mich nah bei dir jeden Tag" },
  { number: 31, name: "Is He worthy" },
  { number: 32, name: "Ein Gott, der redet" },
  { number: 33, name: "Ave Salvator" },
  { number: 34, name: "O the deep, deep love of Jesus" },
  { number: 35, name: "Ich danke meinem Jesus" },
  { number: 36, name: "Kommt und seht Gottes Sohn" },
  { number: 37, name: "Zünde an dein Feuer" },
  { number: 38, name: "Gladly would I leave behind me" },
  { number: 39, name: "Ach wo findet meine Seele" },
  { number: 40, name: "Wenn der König wiederkehrt" },
  { number: 41, name: "Jeden Tag in meinem Leben" },
  { number: 42, name: "All my ways" },
  { number: 43, name: "Danke, mein Vater, für alles" },
  { number: 44, name: "Schöpfer aller Himmel" },
  { number: 45, name: "Nur durch Christus in mir" },
  { number: 46, name: "Heaven is a wonderful place" },
  { number: 47, name: "Welch ein Freund ist unser Jesus" },
  { number: 48, name: "Vater, ich komme jetzt zu dir" },
  { number: 49, name: "Meine Zeit steht in deinen Händen" },
  { number: 50, name: "Lifesong" },
  { number: 51, name: "Wie viel schöne Stunden" },
  { number: 52, name: "Auf deine Gnade, Herr, kommt es an" },
  { number: 53, name: "Du bist der Weg und die Wahrheit" },
  { number: 54, name: "Gott, den niemand anders schuf" },
  { number: 55, name: "Wenn Friede mit Gott meine Seele durchdringt" },
  { number: 56, name: "Christ our hope in life and death" },
  { number: 57, name: "Ich bin bei dir" },
  { number: 58, name: "Sein Kleid für meins" },
  { number: 59, name: "Erstaunlich reich" },
  { number: 60, name: "Lift High The Name Of Jesus" },
  { number: 61, name: "Du gibst das Leben, das sich wirklich lohnt" },
  { number: 62, name: "Hymne der Barmherzigkeit" },
  { number: 63, name: "Von guten Mächten wunderbar geborgen" },
  { number: 64, name: "Von guten Mächten wunderbar geborgen" },
  { number: 65, name: "Lass mir das Ziel vor Augen bleiben" },
  { number: 66, name: "Wenn Gott für uns ist" },
  { number: 67, name: "Nobody" },
  { number: 68, name: "Lobpreis sei ihm" },
  { number: 69, name: "Ich seh das Kreuz" },
  { number: 70, name: "Sei stark, erschrick nicht" },
  { number: 71, name: "Loch im Leben" },
  { number: 72, name: "Bei dir, Jesu, will ich bleiben" },
  { number: 73, name: "Hab Dank von Herzen, Herr" },
  { number: 74, name: "Tag für Tag ermutigt mich aufs Neue" },
  { number: 75, name: "Ancient Of Days" },
  { number: 76, name: "Ach, wer kann dich würdig loben" },
  { number: 77, name: "Bist zu uns wie ein Vater" },
  { number: 78, name: "Ein tägliches Gebet" },
  { number: 79, name: "Folgen" },
  { number: 80, name: "Sein Erbarmen ist noch immer nicht zu Ende" },
  { number: 81, name: "Halleluja, salvation and glory" },
  { number: 82, name: "Ich hab gewählt" },
  { number: 83, name: "Gottes Liebe" },
  { number: 84, name: "Wenn wir doch begreifen würden" },
  { number: 85, name: "Herr aller Hoffnung" },
  { number: 86, name: "Jesus, leite mich mit deinen Augen" },
  { number: 87, name: "Before the throne of God above" },
  { number: 88, name: "Wie tief muss Gottes Liebe sein" },
  { number: 89, name: "Zu deinem Thron, Herr" },
  { number: 90, name: "Nehmt einander an" },
  { number: 91, name: "Wo die Liebe bleibt" },
  { number: 92, name: "He Is" },
  { number: 93, name: "Wer bist du? Was kann ich sagen?" },
  { number: 94, name: "Seit ich dich kenne" },
  { number: 95, name: "Herr Jesus Christus, Licht der Welt" },
  { number: 96, name: "How shall I sing" },
  { number: 97, name: "Lobe den Herrn meine Seele" },
  { number: 98, name: "Gott, dich würdig zu verehren" },
  { number: 99, name: "Ich bin erlöst durch des Lammes Blut" },
  { number: 100, name: "Du bist der einzig wahre und wunderbare Gott" },
  { number: 101, name: "Du bist die Kraft, die mir oft fehlt" },
  { number: 102, name: "Lobe den Herrn! Sing ihm dein Lied!" },
  { number: 103, name: "East To West" },
  { number: 104, name: "Mein Jesus, ich lieb dich" },
  { number: 105, name: "Herr, dein Blut bringt uns Rettung" },
  { number: 106, name: "Für mich gingst du nach Golgatha" },
  { number: 107, name: "Früh am Morgen" },
  { number: 108, name: "River of life" },
  { number: 109, name: "Lege deine Sorgen nieder" },
  { number: 110, name: "Gegen den Strom" },
  { number: 111, name: "Philipper-Hymnus" },
  { number: 112, name: "Auf dem Lamm ruht meine Seele" },
  { number: 113, name: "Christ the sure and steady anchor" },
  { number: 114, name: "Nicht vergebens" },
  { number: 115, name: "Hab auf Hoffnung gebaut" },
  { number: 116, name: "Stark ist meines Jesu Hand" },
  { number: 117, name: "There is a hope" },
  { number: 118, name: "Du bist mein Zufluchtsort" },
  { number: 119, name: "Ein Leben, gegeben" },
  { number: 120, name: "Im Glauben leben" },
  { number: 121, name: "Das erfüllt mich mit Staunen" },
  { number: 122, name: "Jesus lebt, ja, wahrhaftig, Er lebt" },
  { number: 123, name: "Alpha und Omega" },
  { number: 124, name: "Gemeinsam unterwegs" },
  { number: 125, name: "Aus Gnade, nur aus Gnade" },
  { number: 126, name: "Who Am I" },
  { number: 127, name: "Genau an diesem Tag" },
  { number: 128, name: "In Christus ist mein ganzer Halt" },
  { number: 129, name: "Gib mir die richtigen Worte" },
  { number: 130, name: "Above all powers, above all Kings" },
  { number: 131, name: "Altes Wort" },
  { number: 132, name: "Mein Erlöser liebt mich" },
  { number: 133, name: "Es reicht, in Not den Blick zu heben" },
  { number: 134, name: "Herr, durch dein Blut" },
  { number: 135, name: "You Are Holy" },
  { number: 136, name: "Gott ist gut" },
  { number: 137, name: "Fürchte dich nicht, ich bin bei dir" },
  { number: 138, name: "Lobt den Herrn für seine große Güte" },
  { number: 139, name: "There is one Gospel" },
  { number: 140, name: "Nimm dir Zeit, auf Mich zu warten" },
  { number: 141, name: "Sprich, o Herr, denn wir stehn vor dir" },
  { number: 142, name: "Bei dir bin ich angekommen" },
  { number: 143, name: "Ich bin der Weg. Warum gehst du nicht?" },
  { number: 144, name: "O Herr, mein Fels und mein Erlöser" },
  { number: 145, name: "Welch große Weisheit" },
  { number: 146, name: "Jesus, Mitte meines Lebens" },
  { number: 147, name: "Singt ein Lied von Gott" },
  { number: 148, name: "Euer Herz erschrecke nicht" },
  { number: 149, name: "Was für eine Liebe" },
  { number: 150, name: "Dir allein die Ehre" },
  { number: 151, name: "Victory In Jesus" },
  { number: 152, name: "Teil dieser Geschichte" },
  { number: 154, name: "Den Gott uns gab" },
  { number: 155, name: "How Long" },
  { number: 156, name: "Gegenwart" },
  { number: 157, name: "Dir nahe sein ist mein ganzes Glück" },
  { number: 158, name: "Create in me a clean heart" },
  { number: 159, name: "Er ist der Fels" },
  { number: 160, name: "Getragen und geführt" },
  { number: 161, name: "Sing, sing, sing Halleluja" },
  { number: 162, name: "Herr, wenn nicht Du" },
  { number: 163, name: "Schritte in Gottes Spuren" },
  { number: 164, name: "Only a holy God" },
  { number: 165, name: "Da sende Deine Jünger hin" },
  { number: 166, name: "Welche Liebe! Jesus betet" },
  { number: 167, name: "Eigentlich bist Du der König" },
  { number: 168, name: "Brother to brother" },
  { number: 169, name: "Jesus, wir sehen auf dich" },
  { number: 170, name: "Gott ist für uns" },
  { number: 171, name: "Du bist da" },
  { number: 172, name: "Drum ihm zur Ehre" },
  { number: 173, name: "May the peoples praise you" },
  { number: 174, name: "Dort auf Golgatha stand" },
  { number: 175, name: "Seht das herrliche Geheimnis" },
  { number: 176, name: "Vor deinem Kreuz, Herr, will ich stille werden" },
  { number: 177, name: "Durch dein Wort sind entstanden die Sterne" },
  { number: 178, name: "By His wounds" },
  { number: 179, name: "Jakobus-Lied" },
  { number: 180, name: "Begnadigt stehen wir vor Dir" },
  { number: 181, name: "Lob und Dank sei Ihm in Ewigkeit" },
  { number: 182, name: "Der Herr ist mein Hirte, es mangelt mir nicht" },
  { number: 183, name: "The Lord's my Shepherd" },
  { number: 184, name: "Jeder Mensch braucht Gott" },
  { number: 185, name: "Ursprung und Ziel" },
  { number: 186, name: "Christus hält mich fest" },
  { number: 187, name: "Mit weitem Horizont" },
  { number: 188, name: "Saved my soul" },
  { number: 189, name: "Die ganze Schöpfung" },
  { number: 190, name: "Jesus, ich will gehn" },
  { number: 191, name: "Jesus, zu dir kann ich so kommen, wie ich bin" },
  { number: 192, name: "Jesus lebt! Er hat gesiegt" },
  { number: 193, name: "Der auf dem Thron sitzt" },
  { number: 194, name: "Trachtet zuerst nach Gottes Welt" },
  { number: 195, name: "Jesus, thank You" },
  { number: 196, name: "Herr, dein Wort ist lebendig und kräftig" },
  { number: 197, name: "Wenn Perspektiven für mein Leben fehlen" },
  { number: 198, name: "Mitten in Angst und Leid" },
  { number: 199, name: "Das Wort vom Kreuz" },
  { number: 200, name: "Pilgerlied" },
  { number: 201, name: "So sind deine Worte" },
  { number: 202, name: "I Saw The Light" },
  { number: 203, name: "Wenn ich, o Schöpfer, deine Macht" },
  { number: 204, name: "Gottes Wort, ewig wahr" },
  { number: 205, name: "Herr, du verlässt mich nicht" },
  { number: 206, name: "Herr, ich hoff auf Dich" },
  { number: 207, name: "Forgiven" },
  { number: 208, name: "Lob, meine Seel, den Herrn" },
  { number: 209, name: "Unerschaffen" },
  { number: 210, name: "Wie oft hast du mich aufgerichtet" },
  { number: 211, name: "Herr, am Ende dieses Tages" },
  { number: 212, name: "Du großer Gott, wenn ich die Welt betrachte" },
  { number: 213, name: "Perfect Peace" },
  { number: 214, name: "Ich bin entschieden, zu folgen Jesus" },
  { number: 215, name: "Ich bin erlöst" },
  { number: 216, name: "Wenn wir unsre Sünden" },
  { number: 217, name: "Einander begegnen" },
  { number: 218, name: "Mein Leben hier" },
  { number: 219, name: "Nicht durch mich" },
  { number: 220, name: "Ich liebe dich" },
  { number: 221, name: "Möge die Gnade" },
  { number: 222, name: "Herr, wir danken dir" },
  { number: 223, name: "In dir ist Freude" },
  { number: 224, name: "Alle Ehre sei dem König" },
  { number: 225, name: "Wunderbarer Gott" },
  { number: 226, name: "Wir geben dir Ehre" },
  { number: 227, name: "Morgenglanz der Freude" },
  { number: 228, name: "Stille Rast" },
  { number: 229, name: "Zeig uns deine Herrlichkeit" },
  { number: 230, name: "Weil du mich liebst" },
  { number: 231, name: "Frieden" },
  { number: 232, name: "Dein Weg ist höher" },
  { number: 233, name: "Ich bin sicher" },
  { number: 234, name: "Möchtest du heute" },
  { number: 235, name: "Der König naht" },
  { number: 236, name: "Bist du bereit" },
  { number: 237, name: "Gott ist die Liebe" },
  { number: 238, name: "Großer Gott wir loben dich" },
  { number: 239, name: "Herr, dein Wort ist Wahrheit" },
  { number: 240, name: "Sei du mein Weg" },
  { number: 241, name: "Wunderbar" },
  { number: 242, name: "Gemeinsam loben wir" },
  { number: 243, name: "Möge unser Herz" },
  { number: 244, name: "Stark" },
  { number: 245, name: "Gott hat mir viel gegeben" },
  { number: 246, name: "Danke" },
  { number: 247, name: "Segne uns" },
  { number: 248, name: "Alles was ich bin" },
  { number: 249, name: "Leben gefunden" },
  { number: 250, name: "Du hast mich" },
  { number: 251, name: "Wunderbarer Heiland" },
  { number: 252, name: "Rettende Gnade" },
  { number: 253, name: "Erneuet mich" },
  { number: 254, name: "Gnade regiert" },
  { number: 255, name: "Ewigkeitslied" },
  { number: 256, name: "Jesus kehrt zurück" },
  { number: 257, name: "Der Glaube" },
]