import { Song } from "./Contents"

// Ich will dir danken! (g/G)
export const Iwdd: Song[] = [
    { number: 1, name: "Holy, holy, holy! Lord God Almighty" },
    { number: 1, name: "Heilig, heilig, heilig, Gott, Du bist heilig" },
    { number: 2, name: "Heilig, heilig, heilig ist der Herr Zebaoth" },
    { number: 3, name: "Unser Vater in dem Himmel, dir allein" },
    { number: 4, name: "Himmlischer Vater, wir beten Dich an" },
    { number: 4, name: "Heavenly father, I appreciate You" },
    { number: 5, name: "Großer Gott, wir loben dich" },
    { number: 5, name: "Holy God, we praise thy name" },
    { number: 6, name: "Du großer Gott, wenn ich die Welt betrachte" },
    { number: 6, name: "O Lord, my God! When I in awesome wonder" },
    { number: 7, name: "Gott ist immer noch Gott" },
    { number: 8, name: "Vater, ich lieb Dich (Herrlich sei Dein Name)" },
    { number: 9, name: "El Shaddai (Deutsch)" },
    { number: 10, name: "Herr, du mein Gott, du bist gut" },
    { number: 11, name: "Gib Gott die Ehre (Ehre, Ehre sei Gott)" },
    { number: 12, name: "A Dieu soit la gloire (Gloire à Dieu)" },
    { number: 12, name: "O Gott, dir sei Ehre (Preist den Herrn)" },
    { number: 12, name: "To God be the glory (Praise the Lord)" },
    { number: 13, name: "Unser Gott, Dein Name sei gelobt (Alles machst Du neu)" },
    { number: 14, name: "Ewiger Gott, o ewiger Gott, du bist hoch zu loben" },
    { number: 15, name: "Du bist mein Gott, ich will dich preisen" },
    { number: 16, name: "Ich lobe meinen Gott von ganzem Herzen" },
    { number: 17, name: "Immanuel, Immanuel" },
    { number: 18, name: "Gott ist gegenwärtig" },
    { number: 19, name: "Father, we love You (Glorify Your name)" },
    { number: 19, name: "Thou art my God and I will praise Thee" },
    { number: 19, name: "Vater im Himmel, wir beten Dich an (Kanon)" },
    { number: 20, name: "Gott ist allmächtig, drum preiset ihn mein Herz" },
    { number: 21, name: "Wir danken unserm Gott, wir danken unserm Gott (Weil Er uns so liebt)" },
    { number: 22, name: "Let's talk about Jesus" },
    { number: 22, name: "Wir singen von Jesus" },
    { number: 23, name: "Frohlocket all mit lautem Schall und Widerhall" },
    { number: 24, name: "Crown Him with many crowns" },
    { number: 24, name: "Mit allen Kronen krönt das Lamm auf Gottes Thron" },
    { number: 25, name: "Es ist wahr, daß Jesus lebt, Halleluja" },
    { number: 26, name: "Praise Him, praise Him! Jesus, our blessed redeemer" },
    { number: 26, name: "Preist Ihn! Preist Ihn! Jesum, den treuen Erlöser" },
    { number: 27, name: "Du bist das Licht der Welt" },
    { number: 28, name: "Jesus Christus herrscht als König" },
    { number: 29, name: "Schönster Herr Jesu" },
    { number: 30, name: "Anbetung bringen wir dir, Jesus, Gotteslamm" },
    { number: 31, name: "Sein Nam' ist höher als jeder andre" },
    { number: 31, name: "His name is higher than any other" },
    { number: 32, name: "Ist's wirklich wahr, daß mir zugut der Heiland starb" },
    { number: 32, name: "And can it be that I should gain" },
    { number: 33, name: "Unerschöpflich strömt die Quelle (Dir sei Ehre)" },
    { number: 33, name: "When I saw the cleansing fountain (I will praise Him)" },
    { number: 34, name: "Wir sind eins in dem Geist und wir sind eins in dem Herrn" },
    { number: 35, name: "We are gathering together unto Him" },
    { number: 35, name: "Wir versammeln uns zu dir, o großer Gott" },
    { number: 36, name: "Kommt, stimmet alle jubelnd ein" },
    { number: 37, name: "Jesus, du, des Lebens Herr" },
    { number: 38, name: "Jesus, Dir gehört mein Leben und Lobpreis" },
    { number: 39, name: "Majesty, worship His Majesty" },
    { number: 39, name: "Majestät, herrliche Majestät" },
    { number: 40, name: "All die Fülle ist in dir, o Herr" },
    { number: 41, name: "Oh, sing to the Lord! Oh, sing God a new song" },
    { number: 41, name: "Kommt, singt unserm Herrn! Ein neues Lied bringt Ihm" },
    { number: 41, name: "Cantad al Senor un cántico nuevo" },
    { number: 42, name: "Ich will dir danken (Gott, mein Herr, es ist mir ernst)" },
    { number: 43, name: "Groß ist dein Name, Herr, wir loben dich (Er selber, Gottes Sohn)" },
    { number: 44, name: "Lob, meine Seel, den Herrn" },
    { number: 45, name: "Für dich sei ganz mein Herz und Leben (Ich bete an die Macht der Liebe)" },
    { number: 46, name: "His name is Wonderful" },
    { number: 46, name: "Sein Nam' heißt Wunderbar" },
    { number: 47, name: "Thou art worthy, Thou art worthy" },
    { number: 47, name: "Du bist würdig, Du bist würdig" },
    { number: 48, name: "Lobe den Herren, den mächtigen König der Ehren" },
    { number: 49, name: "Du meine Seele, singe" },
    { number: 50, name: "Auf, Christen, stimmt ein Loblied an" },
    { number: 51, name: "Nie mehr wirst Du von uns weichen" },
    { number: 52, name: "Es beten dich an, die im Himmel, die auf der Erde" },
    { number: 53, name: "Halleluja, Halleluja! Jesus Christus, wir loben Dich" },
    { number: 54, name: "I will sing of the mercies of the Lord" },
    { number: 54, name: "Ich will singen von der Gnade meines Herrn" },
    { number: 55, name: "O lasst uns mit Jauchzen erheben" },
    { number: 56, name: "Juble, mein Herz, ich habe den Heiland gefunden" },
    { number: 57, name: "O daß ich tausend Zungen hätte" },
    { number: 58, name: "Lob und Dank, Lob und Dank" },
    { number: 59, name: "Vergiss nicht zu danken" },
    { number: 60, name: "Herr, Du hast Großes an uns hier getan (Herrlichkeit Dir, Jesu, allein)" },
    { number: 61, name: "Unser Mund, der ist voll Jubel" },
    { number: 62, name: "Halleluja, Halleluja! Singt und jubelt eurem Herrn (Singt Halleluja)" },
    { number: 63, name: "Nun danket alle Gott" },
    { number: 63, name: "Now thank we all our God" },
    { number: 64, name: "O Gott, sei gelobt für die Liebe im Sohn (Halleluja, sei gepriesen)" },
    { number: 65, name: "Amazing Grace (Amazing grace, how sweet the sound, that saved a wretch like me.)" },
    { number: 65, name: "O Gnade Gottes, wunderbar" },
    { number: 66, name: "Ich singe dir mit Herz und Mund" },
    { number: 67, name: "Sing mit mir ein Halleluja (Für die Ruhe in der Nacht)" },
    { number: 68, name: "O, hätt ich tausend Zungen nur" },
    { number: 69, name: "Ich will Dir danken, Herr (Sei erhoben, o Gott)" },
    { number: 69, name: "Je t'exalterai, Seigneur (Seigneur, élève toi)" },
    { number: 69, name: "I will give thanks to Thee (Be exalted, o God)" },
    { number: 70, name: "Danke, mein Vater, für alles, was Du schenkst" },
    { number: 71, name: "Verlasst euch stets auf den Herrn, denn der Herr ist ein ewiger Fels (Kanon)" },
    { number: 72, name: "Dass du mich einstimmen lässt in deinen Jubel, o Herr" },
    { number: 73, name: "Die Herrlichkeit des Herrn bleibe ewiglich (Kanon)" },
    { number: 73, name: "Let the glory of the Lord endure forever" },
    { number: 74, name: "Wüst ist das Land (Dankt dem Herrn Zebaoth)" },
    { number: 75, name: "Bleibend ist deine Treu" },
    { number: 75, name: "Great is Thy faithfulness" },
    { number: 76, name: "Dir, Herr, sei das Lob, das aus der Tiefe zu Dir dringt" },
    { number: 77, name: "Blagadarim Gaspodj" },
    { number: 77, name: "Jesus, wir danken Dir, Jesus, wir danken Dir" },
    { number: 78, name: "Steht auf und lobt unsern Gott" },
    { number: 79, name: "Lobet und preiset, ihr Völker, den Herrn" },
    { number: 80, name: "Lob, Ehr und Preis dir, Gottes Lamm" },
    { number: 81, name: "Danke, Herr Jesus (Allen Kummer, alle Sorgen sag ich dir, mein Herr und Gott)" },
    { number: 82, name: "Jesus, höchster Name" },
    { number: 82, name: "Jesus, name above all names" },
    { number: 83, name: "Er ist der Friedefürst und der allmächtge Gott" },
    { number: 84, name: "Jesus, Dir nur will ich singen (Ehre, Ehre, Preis, Anbetung)" },
    { number: 85, name: "Wohl dem, der nicht wandelt" },
    { number: 86, name: "Der Herr, mein Hirte, führet mich" },
    { number: 87, name: "Denn du bist groß, ein Gott, der Wunder tut" },
    { number: 88, name: "Lobe den Herrn, meine Seele, und Seinen heiligen Namen" },
    { number: 89, name: "Bei Dir ist die Quelle des Lebens" },
    { number: 90, name: "Das ist meine Freude (Aber das ist meine Freude, dass ich mich zu Gott halte)" },
    { number: 91, name: "Der Herr denkt an uns" },
    { number: 92, name: "Psalm 150 (Halleluja! Lobet Gott in Seinem Heiligtum)" },
    { number: 93, name: "Seid still und erkennt, dass ich Gott bin" },
    { number: 94, name: "Dennoch bleibe ich bei Dir" },
    { number: 94, name: "I'll be with You, You will guide me" },
    { number: 95, name: "Der Herr ist mein Licht und mein Heil" },
    { number: 96, name: "Ich trau auf Dich, oh Herr" },
    { number: 97, name: "Und dennoch bleibe ich stets bei Dir" },
    { number: 98, name: "Dein Wort ist meines Fußes Leuchte" },
    { number: 99, name: "Groß und wunderbar" },
    { number: 100, name: "Verlasst euch stets auf den Herrn" },
    { number: 101, name: "O for a thousand tongues to sing" },
    { number: 101, name: "Wo ist solch ein Gott? (Lei lei lei lei lei...)" },
    { number: 102, name: "Die dem Herrn vertrauen, schöpfen neue Kraft" },
    { number: 103, name: "Wenn mein Volk, über das mein Name genannt ist" },
    { number: 104, name: "Herr, dein Wort, die edle Gabe" },
    { number: 105, name: "Selig sind, die reinen Herzens sind" },
    { number: 106, name: "Seek ye first the kingdom of God" },
    { number: 106, name: "Trachtet zuerst nach Gottes Reich" },
    { number: 107, name: "Vater, ich will dich preisen" },
    { number: 108, name: "Ein neu' Gebot" },
    { number: 109, name: "Fürchte dich nicht, denn du bist mein" },
    { number: 110, name: "Die Güte des Herrn hat kein Ende" },
    { number: 111, name: "Ihr seid das Salz der Erde, ihr seid das Licht der Welt" },
    { number: 112, name: "Dein Wort kommt niemals leer zurück" },
    { number: 113, name: "Fels des Heils, geöffnet mir" },
    { number: 113, name: "Rock of ages, cleft for me" },
    { number: 114, name: "Wir wollen Deinen Tod verkünden" },
    { number: 115, name: "Lasst uns feiern das Mahl, das Er uns gab" },
    { number: 116, name: "Nehmt und esst" },
    { number: 117, name: "Jesus nahm das Brot und gab es Seinen Jüngern" },
    { number: 118, name: "Dem König, welcher Blut und Leben" },
    { number: 119, name: "Es ist ein Born, draus heilges Blut" },
    { number: 120, name: "Segen (Herr, segne uns und behüte uns)" },
    { number: 121, name: "Herr, mein ganzes Leben soll dir Ehre geben (Kanon)" },
    { number: 121, name: "Father, I adore You" },
    { number: 122, name: "Jesu Friede sei mit allen" },
    { number: 123, name: "Segne uns, o Herr" },
    { number: 124, name: "Jesus Christus segne dich" },
    { number: 125, name: "Gott, der Vater, kröne dich" },
    { number: 126, name: "Christus, der Herr aller Welt (Unser gemeinsamer Herr)" },
    { number: 127, name: "Wo zwei oder drei in meinem Namen versammelt sind" },
    { number: 128, name: "Friede, Friede, Friede sei mit dir (Nicht jenes Warten, wenn die Waffen schweigen...)" },
    { number: 129, name: "Du zeigst mir den Weg zum Leben" },
    { number: 130, name: "Geh unter der Gnade (Alte Stunden alte Tage...)" },
    { number: 131, name: "Siehe, ich mache alles neu" },
    { number: 132, name: "Himmel und Erde müssen vergehn (Kanon)" },
    { number: 133, name: "Herr, wir bitten: Komm und segne uns" },
    { number: 134, name: "Macht hoch die Tür" },
    { number: 135, name: "Advent ist es heut" },
    { number: 136, name: "Freue dich, Welt, dein König naht" },
    { number: 136, name: "Joy to the world" },
    { number: 137, name: "Wie soll ich dich empfangen" },
    { number: 138, name: "Mache dich auf und werde licht" },
    { number: 139, name: "In eine Welt voller Dunkelheit" },
    { number: 140, name: "O Du mein Trost und süßes Hoffen" },
    { number: 141, name: "Jesus ist kommen, Grund ewiger Freude" },
    { number: 142, name: "Die Nacht ist vorgedrungen" },
    { number: 143, name: "König der Herrlichkeit, König der Ehren" },
    { number: 144, name: "Tochter Zion, freue dich" },
    { number: 145, name: "So sehr liebt uns Gott, Er sandte Seinen Sohn" },
    { number: 146, name: "In der Nacht von Bethlehem" },
    { number: 147, name: "Der Heiland ist geboren (Freut euch von Herzen)" },
    { number: 148, name: "Schönster Herr Jesu (Kanon)" },
    { number: 149, name: "Unser Heiland ist nun da" },
    { number: 149, name: "Hark! the herald angels sing" },
    { number: 150, name: "Noel, Noel, Noel, Noel, born ist the king of Israel" },
    { number: 150, name: "Noel, Noel, Noel, Noel, Christ ist geboren" },
    { number: 151, name: "Stille Nacht, heilige Nacht" },
    { number: 152, name: "Ich steh an deiner Krippen hier" },
    { number: 153, name: "O come, all ye faithful" },
    { number: 153, name: "Herbei, o ihr Gläub'gen (Herbei, o ihr Gläubigen)" },
    { number: 154, name: "Freude, große Freude leuchtet aus der Nacht" },
    { number: 155, name: "Gloria, Gloria, Jesus, mein König, ist da" },
    { number: 156, name: "Fröhlich soll mein Herze springen" },
    { number: 157, name: "Danket, danket dem Herrn (Kanon)" },
    { number: 158, name: "Gott wurde arm für uns" },
    { number: 159, name: "Engel bringen frohe Kunde (Gloria in excelsis Deo)" },
    { number: 160, name: "O du fröhliche, o du selige" },
    { number: 161, name: "Ein Jahr geht nach dem andern hin" },
    { number: 162, name: "Das Jahr geht still zu Ende" },
    { number: 163, name: "In der Welt habt ihr Angst, aber seid getrost" },
    { number: 164, name: "Mit dem Herrn fang alles an" },
    { number: 165, name: "Mein Herr kennt den Weg, der vor mir liegt" },
    { number: 166, name: "Von guten Mächten wunderbar geborgen" },
    { number: 167, name: "Es eilt die Zeit (Komm, eh der letzte Tag versinkt)" },
    { number: 168, name: "Er geht voran, er hat's verheißen" },
    { number: 169, name: "O Haupt voll Blut und Wunden" },
    { number: 170, name: "O Du Lamm Gottes, das da getragen" },
    { number: 171, name: "Jesus Christus starb für mich" },
    { number: 172, name: "Für mich gingst Du nach Golgatha (Herr, Deine Liebe ist so groß)" },
    { number: 173, name: "Ich rief zu dem Herrn in meiner Angst" },
    { number: 174, name: "Eines wünsch ich mir vor allem andern" },
    { number: 175, name: "Was Gott nimmt, das reinigt Er" },
    { number: 176, name: "O Du Lamm Gottes, du hast auf Golgatha" },
    { number: 177, name: "Das Kreuz, es stehet fest (Halleluja, rühmt das Kreuz)" },
    { number: 178, name: "Alles, was atmen kann, lobe den Herrn" },
    { number: 179, name: "Schau ich zu deinem Kreuze hin" },
    { number: 180, name: "Kennst Du den Weg zum Kreuz auf Golgatha" },
    { number: 181, name: "When I survey the wondrous cross" },
    { number: 181, name: "Am Kreuz litt Er für mich (Jesus, mein Heiland, lebt)" },
    { number: 181, name: "Low in the grave He lay (Up from the grave He arose)" },
    { number: 182, name: "Freuet euch, das Grab ist leer" },
    { number: 183, name: "Lasst uns loben den Namen des Herrn (Kanon)" },
    { number: 184, name: "Auferstanden aus des Grabes Nacht (Und wir werden mit Ihm leben)" },
    { number: 185, name: "Er ist Herr" },
    { number: 185, name: "He is Lord, He is Lord" },
    { number: 186, name: "Seele, dein Heiland ist frei von den Banden (Jesus, dein Heiland, ist Sieger und lebt)" },
    { number: 187, name: "Mit Jauchzen freuet euch (Singt laut das Lied vom Sieg und Reich)" },
    { number: 188, name: "Jesus lebt, mit ihm auch ich" },
    { number: 189, name: "Er ist erstanden, Halleluja" },
    { number: 190, name: "Der Herr ist auferstanden (Er ist wahrhaftig auferstanden)" },
    { number: 191, name: "Seid nicht bekümmert" },
    { number: 192, name: "Christus ist auferstanden, wahrhaftig auferstanden" },
    { number: 193, name: "Jesus Christus ist der Sieger über Sünde, Tod und Teufel" },
    { number: 194, name: "Der Herr fährt auf gen Himmel mit frohem Jubelschall" },
    { number: 195, name: "Der Herr ist aufgefahren zum Thron der Herrlichkeit" },
    { number: 196, name: "Jesus ist Sieger, mit goldenen Lettern" },
    { number: 197, name: "Herr, befreie unsre Herzen, Dir zu danken" },
    { number: 198, name: "Mächtige Ströme des Segens" },
    { number: 198, name: "There shall be showers of blessing (Showers of blessing)" },
    { number: 199, name: "O Gott, o Geist, o Licht des Lebens" },
    { number: 200, name: "O komm, du Geist der Wahrheit" },
    { number: 201, name: "Wir heißen deine Kinder und folgen dir nicht mehr" },
    { number: 202, name: "Herr, wohin soll'n wir gehn" },
    { number: 203, name: "I have decided to follow Jesus" },
    { number: 203, name: "Ich bin entschieden, zu folgen Jesus" },
    { number: 204, name: "Lass mir das Ziel vor Augen bleiben (Bin ich versucht, auf mich zu schauen)" },
    { number: 205, name: "Erwählet euch heute, wem Ihr dienen wollt" },
    { number: 206, name: "Herr, wir sind zu dir gekommen, um in deinem Dienst zu stehn" },
    { number: 207, name: "Nimm mein Leben, Jesu, dir übergeb ich's für und für" },
    { number: 207, name: "Take my life, and let it be consecrated" },
    { number: 208, name: "Behalte mich in Deiner Pflege" },
    { number: 209, name: "Ich möcht ein Segen sein mehr, als ich war" },
    { number: 210, name: "Ich sage Ja zu Dir (Jesus Christus, mein Gott und mein Herr)" },
    { number: 211, name: "Wir leben und wirken und halten zusammen" },
    { number: 212, name: "Nimm Du mich ganz hin, o Gottessohn" },
    { number: 213, name: "Komm, geh mit mir in das Land" },
    { number: 214, name: "Praise the name of Jesus" },
    { number: 214, name: "Preist den Namen Jesus" },
    { number: 215, name: "Keinem von uns ist Gott fern (Ist dir Gott noch unbekannt)" },
    { number: 216, name: "Die Möwen, sie fliegen (Doch Gott hält für uns eine Wohnung bereit)" },
    { number: 217, name: "So wie ich bin, so muß es sein" },
    { number: 217, name: "Just as I am, without one plea" },
    { number: 218, name: "Hört den großen starken Namen: Jesus Christus, Gott und Herr" },
    { number: 219, name: "Kommt, singt mit uns das Lied der Freude" },
    { number: 220, name: "Such, wer da will, ein ander Ziel" },
    { number: 221, name: "Wer Jesus am Kreuze im Glauben erblickt" },
    { number: 222, name: "Would you be free from your burden of sin (There is power)" },
    { number: 222, name: "Möchtest du los sein vom Banne der Sünd (Es ist Kraft, Kraft, wunderbare Kraft)" },
    { number: 223, name: "Jesus Christus kennt dich, er allein weiß, was dir fehlt" },
    { number: 224, name: "Kehret um, kehret um, und ihr werdet leben" },
    { number: 225, name: "Fröhlich zieh ich meine Straße" },
    { number: 226, name: "O wende dich zu Jesu hin" },
    { number: 227, name: "Es ist niemand zu groß (Gott öffnet jedem die Tür)" },
    { number: 228, name: "Gestern, heute und für immer gleich" },
    { number: 229, name: "Hört, wen Jesus glücklich preist, Halleluja" },
    { number: 230, name: "Es geht ohne Gott in die Dunkelheit (Als die Welt noch jung war)" },
    { number: 231, name: "Dir fehlt wohl noch der Friede (O daß du könntest glauben)" },
    { number: 232, name: "Sag nicht nein. Gott ruft auch dich (Sieh, Er liebt dich)" },
    { number: 233, name: "Heute will dich Jesus fragen (Wag es mit Jesus)" },
    { number: 234, name: "Hast du den rechten Kurs für dein Leben (Wiedergeboren zu neuem Leben)" },
    { number: 235, name: "Siehe, Ich stehe vor der Tür und klopfe an" },
    { number: 236, name: "Gott lädt uns ein (Leben im Schatten)" },
    { number: 237, name: "Ich weiß einen Strom (O Seele, ich bitte dich: Komm)" },
    { number: 238, name: "Mag sein, du kannst es nicht verstehn" },
    { number: 239, name: "Noch dringt Jesu frohe Botschaft (Jesus Christus, Heiland und Erlöser)" },
    { number: 240, name: "Viele suchen dies und das (Steck den Kopf nicht in den Sand)" },
    { number: 241, name: "Sag, kennst du wohl den wunderbaren Namen (Name über alle Namen)" },
    { number: 242, name: "Gepriesen sei der Herr" },
    { number: 243, name: "Come with thy sins to the fountain (Haste thou away)" },
    { number: 243, name: "Komm doch zur Quelle des Lebens (Eile dahin)" },
    { number: 244, name: "Ich bin nicht irgendwer und nicht von ungefähr" },
    { number: 244, name: "Freuet euch in dieser Zeit" },
    { number: 245, name: "Gott hat uns geschaffen (Grenzenlose Freude)" },
    { number: 246, name: "Jesus kam, uns zu erlösen, preiset den Herrn" },
    { number: 247, name: "Gnade, die Jesus uns zugewandt (Gnade, Gnade)" },
    { number: 248, name: "Nichts habe ich, was nicht frei ich empfing (Einer, der Gottes Gnade fand)" },
    { number: 249, name: "Wie ein Fest nach langer Trauer (So ist Versöhnung)" },
    { number: 250, name: "On a hill far away (O that old rugged cross)" },
    { number: 250, name: "Dort auf Golgatha stand (Schätzen werd ich das alt rauhe Kreuz)" },
    { number: 251, name: "Vom Kreuz zeigt Jesus den Weg uns nach Haus (Vom Kreuz führt ein Weg nach Haus)" },
    { number: 252, name: "Christi Blut und Gerechtigkeit" },
    { number: 253, name: "Welch Glück ist's, erlöst zu sein (O preist Seiner Liebe Macht)" },
    { number: 254, name: "Mir ist Erbarmung widerfahren" },
    { number: 255, name: "Siehe, Ich habe dir geboten" },
    { number: 256, name: "Jesus, Dir nach, weil Du rufst" },
    { number: 257, name: "Ich habe nun den Grund gefunden" },
    { number: 258, name: "Jésus Christ, fils de Dieu (Merci notre Père)" },
    { number: 258, name: "There is a redeemer" },
    { number: 258, name: "Er ist der Erlöser" },
    { number: 259, name: "Die Gott lieben, werden sein wie die Sonne" },
    { number: 260, name: "Jesus lebet, Jesus siegt" },
    { number: 261, name: "Unser Glaube ist der Sieg" },
    { number: 262, name: "Bei Dir, dem Weinstock (Ich möchte bei dir bleiben)" },
    { number: 263, name: "Folge niemals dem Rat der gottlosen Leute (Dann wirst du sein wie ein Baum an der Quelle)" },
    { number: 264, name: "Ich lieb dich, Herr, keiner ist wie du" },
    { number: 265, name: "Viele Wege (Weise mir, Herr, Deinen Weg)" },
    { number: 266, name: "Blessed assurance, Jesus is mine (This is my story)" },
    { number: 266, name: "Seligstes Wissen: Jesus ist mein (Lasst mich's erzählen, Jesus zur Ehr)" },
    { number: 267, name: "Näher, mein Gott, zu dir" },
    { number: 267, name: "Nearer, my God, to Thee" },
    { number: 268, name: "Näher, noch näher" },
    { number: 268, name: "Nearer, still nearer" },
    { number: 269, name: "Nun gehören unsre Herzen" },
    { number: 270, name: "Meinen Jesus laß ich nicht" },
    { number: 271, name: "Jesu, geh voran" },
    { number: 272, name: "Ich brauch dich allezeit" },
    { number: 273, name: "Ich liebe Jesum alle Stund" },
    { number: 274, name: "Herr, füll mich neu" },
    { number: 275, name: "Prüfe mich, Herr, erforsche Du mein Herz" },
    { number: 276, name: "Du bist der Weg und die Wahrheit und das Leben" },
    { number: 277, name: "Bei dir, Jesu, will ich bleiben" },
    { number: 278, name: "Friede mit euch, Friede mit euch" },
    { number: 279, name: "Es ist gut, auf den Herrn zu vertrauen" },
    { number: 280, name: "Jesus, Du mein Leben, meines Herzens Streben" },
    { number: 281, name: "Immer auf Gott zu vertrauen" },
    { number: 282, name: "Geh, Abraham, geh" },
    { number: 283, name: "Mein Jesus, ich lieb dich" },
    { number: 283, name: "My Jesus, I love Thee, I know Thou art mine" },
    { number: 284, name: "Preis den Herrn, meine Seele" },
    { number: 285, name: "Jesus, wir sehen auf dich" },
    { number: 286, name: "Wachet auf, ruft uns die Stimme" },
    { number: 287, name: "Lass mich dein sein und bleiben" },
    { number: 288, name: "Zeichen der Liebe (Seid fröhlich in der Hoffnung)" },
    { number: 289, name: "Erforsche mich, Gott, und erkenne mein Herz" },
    { number: 290, name: "Herr, Du hast uns gerufen (Rede mit uns allezeit)" },
    { number: 291, name: "Und dennoch, wenns auch tobt und stürmt" },
    { number: 292, name: "Vom Himmel her kam ein Kind (Du, unser Gott, Du bist der Herr)" },
    { number: 292, name: "The Servant King (From heaven You came)" },
    { number: 293, name: "Vom Himmel kam Er zu uns (Du großer König Jesus Christ)" },
    { number: 294, name: "Jesus, mein Herr, wird immer mich lieben (Darum gehör ich Jesus)" },
    { number: 295, name: "The greatest thing in all my life" },
    { number: 295, name: "Das Höchste meines Lebens" },
    { number: 296, name: "Bind uns zusammen, Herr" },
    { number: 297, name: "Jesu Name nie verklinget" },
    { number: 298, name: "Jesu, meine Freude, meines Herzens Weide" },
    { number: 299, name: "Blicke nur auf Jesus, Seele, eil ihm zu" },
    { number: 300, name: "Jesus ist immer noch größer" },
    { number: 301, name: "Jesu, hilf siegen, du Fürste des Lebens" },
    { number: 302, name: "Brüder, noch gilt es zu retten (Auf Brüder, glauben heißt siegen)" },
    { number: 303, name: "Hast du eine Sorgenlast" },
    { number: 304, name: "Keiner wird zuschanden, welcher Gottes harrt" },
    { number: 305, name: "Fest und treu, wie Daniel war (Bleibe fest, wie Daniel)" },
    { number: 306, name: "Revive Thy work, o Lord" },
    { number: 306, name: "Beleb dein Werk, o Herr" },
    { number: 307, name: "Ja, ich glaub, Gott hört Gebet" },
    { number: 308, name: "Geduld ist euch vonnöten" },
    { number: 309, name: "Jesus, Heiland meiner Seele" },
    { number: 310, name: "Die Gnade sei mit allen" },
    { number: 311, name: "A mighty fortress is our God" },
    { number: 311, name: "Ein feste Burg ist unser Gott" },
    { number: 312, name: "Ich freue mich, ich freu mich" },
    { number: 313, name: "Dass Jesus siegt, bleibt ewig ausgemacht" },
    { number: 314, name: "Welch ein Freund ist unser Jesus" },
    { number: 314, name: "What a friend we have in Jesus" },
    { number: 315, name: "Von Freiheit will ich singen" },
    { number: 316, name: "Work, for the night is coming" },
    { number: 316, name: "Auf, denn die Nacht wird kommen" },
    { number: 317, name: "Wir sehen die verlorene Welt" },
    { number: 317, name: "The vision of a dying world" },
    { number: 318, name: "Die Sach ist dein, Herr Jesu Christ" },
    { number: 319, name: "Du bist der Weg, und Du führst zur Wahrheit" },
    { number: 320, name: "Hast du Jesu Ruf vernommen" },
    { number: 321, name: "Jesus, ich will gehn, sende mich" },
    { number: 322, name: "Wir schämen uns der Botschaft nicht" },
    { number: 323, name: "Jesus ist der schönste Nam" },
    { number: 324, name: "Jesus sucht Leute" },
    { number: 325, name: "Stimmt zu Gottes Ehren froh ein Loblied an" },
    { number: 326, name: "Jetzt ist die Zeit zu bauen" },
    { number: 327, name: "Vom Aufgang der Sonne" },
    { number: 328, name: "Siehe, Finsternis bedeckt die Erde" },
    { number: 329, name: "Wach auf, du Geist der ersten Zeugen" },
    { number: 330, name: "Herr, Du gibst uns Hoffnung, Du änderst unser Leben" },
    { number: 331, name: "Du gibst das Leben, das sich wirklich lohnt" },
    { number: 332, name: "Befiehl dem Herrn deine Wege (Kanon)" },
    { number: 333, name: "Jesus ist immer da, er ist dir heute nah" },
    { number: 334, name: "Die Güte Gottes preisen soll meine Freude sein" },
    { number: 335, name: "Sende dein Licht und deine Wahrheit" },
    { number: 336, name: "Meine Zeit steht in Deinen Händen" },
    { number: 337, name: "Rufe mich an in der Not (Kanon)" },
    { number: 338, name: "Sag ja zu Gottes Wegen, Gottes Wege sind immer gut" },
    { number: 339, name: "O Heiland, fülle meinen Tag (In keinem andern ist ja Heil)" },
    { number: 340, name: "Fröhlich, fröhlich ist das Volk" },
    { number: 341, name: "Herr, manche Tage sind für mich eine Last" },
    { number: 342, name: "Hell strahlt die Sonne" },
    { number: 343, name: "Ein neuer Tag beginnt, und ich freu mich (Warst die ganze Nacht mir nah)" },
    { number: 344, name: "Dies ist der Tag, dies ist der Tag, den der Herr gemacht" },
    { number: 345, name: "Danke für diesen guten Morgen" },
    { number: 346, name: "Die güldne Sonne" },
    { number: 347, name: "Lass mich Dir singen, Herr" },
    { number: 348, name: "Er weckt mich alle Morgen" },
    { number: 349, name: "Die Sonne sinkt, die Gnade nicht" },
    { number: 350, name: "Herr, bleib bei mir, der Abend bricht herein (Bleib bei mir, Herr!)" },
    { number: 351, name: "Mein schönste Zier und Kleinod" },
    { number: 352, name: "Nun wollen wir singen das Abendlied" },
    { number: 353, name: "Diesen Tag, Herr, leg ich zurück in Deine Hände" },
    { number: 354, name: "Es wird Abend, schlafen geht die Welt" },
    { number: 355, name: "Abend ward, bald kommt die Nacht" },
    { number: 356, name: "Bleibe bei uns, denn es wird Nacht (Mutlos und traurig)" },
    { number: 357, name: "Toben auch Stürme" },
    { number: 358, name: "When all my labors and trials are over (O that will be glory for me)" },
    { number: 358, name: "Wenn nach der Erde Leid, Arbeit und Pein (Das wird allein Herrlichkeit sein)" },
    { number: 359, name: "Bald schon kann es sein, dass wir Gott als König sehn" },
    { number: 360, name: "Keiner weiß, wann" },
    { number: 361, name: "Wir haben eine Hoffnung (Jesus kommt wieder)" },
    { number: 362, name: "Du sollst nicht müde werden (Wir werden sein wie die Träumenden)" },
    { number: 363, name: "Wir warten dein, o Gottessohn" },
    { number: 364, name: "Dann wird es kein Leid mehr geben (Gott wird sein alles und in allen)" },
    { number: 365, name: "Soon and very soon" },
    { number: 365, name: "Mine eyes have seen the glory (Glory! glory! hallelujah)" },
    { number: 365, name: "Viele Augen warten heute (Ehre, Ehre Seinem Namen)" },
    { number: 366, name: "Lobpreiset unsern Gott (Freuet euch, ich komm)" },
    { number: 367, name: "Lass mich an dich glauben, wie Abraham es tat" },
    { number: 368, name: "Du bist mein Ziel, mein Gott" },
    { number: 369, name: "Mein Glaube fest sich bauen kann (Wer diesem Felsen fest vertraut)" },
    { number: 369, name: "My hope is built on nothing less (On Christ, the solid rock, I stand)" },
    { number: 370, name: "Solang mein Jesus lebt (So lang mein Jesus lebt)" },
    { number: 371, name: "Wir haben einen Felsen, der unbeweglich steht" },
    { number: 372, name: "Stern, auf den ich schaue" },
    { number: 373, name: "Denn ich bin gewiss, dass weder Tod noch Leben" },
    { number: 374, name: "Im Kreuz ist unsre Kraft verborgen (Denn die da harren auf den Herrn)" },
    { number: 375, name: "Ich steh in meines Herren Hand" },
    { number: 376, name: "So nimm denn meine Hände" },
    { number: 377, name: "Aber der Herr ist immer noch größer (Wellen der Angst)" },
    { number: 378, name: "Herr, weil mich festhält deine starke Hand" },
    { number: 379, name: "Im Glauben und Vertrauen" },
    { number: 380, name: "Wie tief kann ich fallen (Nie tiefer als in Gottes Hand)" },
    { number: 381, name: "Wer Gott folgt, riskiert seine Träume" },
    { number: 382, name: "Glauben heißt vertrauen Gottes Vaterhut" },
    { number: 383, name: "Wohl denen, die da wandeln" },
    { number: 384, name: "Es sind der Gaben auf Erden viel" },
    { number: 385, name: "Jesus nur alleine sei mein Losungswort" },
    { number: 386, name: "Freu dich an der Sonne (Ich habe Freude, ja Freude, die bis morgen bleibt)" },
    { number: 387, name: "Suchet den Herrn, so werdet ihr leben (Kanon)" },
    { number: 388, name: "In dir ist Freude" },
    { number: 389, name: "Wir bekümmern uns nicht, denn die Freude am Herrn" },
    { number: 390, name: "Richte unsre Füße auf den Weg des Friedens (Siehe, ich breite aus den Frieden)" },
    { number: 391, name: "Wie das Licht nach der Nacht" },
    { number: 392, name: "Weiß ich den Weg auch nicht" },
    { number: 393, name: "Dank sei dir, ja, Dank sei dir" },
    { number: 394, name: "Ich blicke voll Beugung und Staunen" },
    { number: 395, name: "Dankt dem Herrn mit frohem Mut" },
    { number: 396, name: "Du hast mein Leben so reich gemacht" },
    { number: 397, name: "When peace like a river (It is well with my soul)" },
    { number: 397, name: "Wenn Friede mit Gott meine Seele durchdringt (Mir ist wohl in dem Herrn)" },
    { number: 398, name: "Like a river, glorious (Stayed upon Jehovah)" },
    { number: 398, name: "Wie ein Strom von oben" },
    { number: 399, name: "Ich will den Namen des Herrn preisen" },
    { number: 400, name: "Nun aufwärts froh den Blick gewandt" },
    { number: 401, name: "Father, make us one" },
    { number: 401, name: "Vater, mach uns eins, Vater, mach uns eins, dass die Welt erkennt" },
    { number: 402, name: "O Herr, ich habe lieb die Stätte Deines Hauses" },
    { number: 403, name: "Du hast uns als Gemeinde in Deinen Dienst gestellt" },
    { number: 404, name: "The church's one foundation" },
    { number: 404, name: "Die Kirche steht gegründet allein auf Jesum Christ" },
    { number: 405, name: "Selig sind, die Frieden stiften" },
    { number: 406, name: "Wenn Gott will und wir leben" },
    { number: 407, name: "Gut, dass wir einander haben" },
    { number: 408, name: "Ein jeder trage die Last des andern" },
    { number: 409, name: "Lasset uns Ihn lieben" },
    { number: 410, name: "Er hat mich so geliebt" },
    { number: 410, name: "Gott baut Sein Haus, Stein auf Stein" },
    { number: 411, name: "Herz und Herz vereint zusammen" },
    { number: 412, name: "Ich will einziehn in sein Tor" },
    { number: 412, name: "I will enter His gates" },
    { number: 413, name: "Der Tempel (Jesus will uns bau'n zu einem Tempel)" },
    { number: 414, name: "Es pilgert durch die Lande" },
    { number: 415, name: "Ich will loben Jesus, solange ich lebe" },
    { number: 416, name: "Herr, wir stehen Hand in Hand" },
    { number: 417, name: "Überwunden durch das Blut (Triumphierend brach das Lamm Satans Macht entzwei)" },
    { number: 418, name: "Lass du mich stille werden, mein Herr und Gott" },
    { number: 419, name: "Erforsche mich, Jesu, mein Licht" },
    { number: 420, name: "Nicht der Anfang, nur das Ende" },
    { number: 421, name: "Der Herr ist treu (Kanon)" },
    { number: 422, name: "Herr, halte mich nah bei Dir jeden Tag (Herr, mach aus mir ein Gefäß)" },
    { number: 423, name: "Unser Herr sagt uns in Seinem Wort (Wenn wir fest mit Ihm verbunden sind)" },
    { number: 424, name: "Du allein bist Gott. Dir gehört die Macht" },
    { number: 425, name: "Dass dein Wort in meinem Herzen" },
    { number: 426, name: "Nicht mehr mein Ich, sondern Christus lebt in mir" },
    { number: 427, name: "Gib mir Liebe ins Herz, lass mich leuchten (Sing Hosianna)" },
    { number: 428, name: "Shine, Jesus, shine (Lord, the light of Your love)" },
    { number: 428, name: "Herr, das Licht Deiner Liebe leuchtet auf (Jesus, dein Licht)" },
    { number: 429, name: "Heilge Liebe, unaussprechlich" },
    { number: 430, name: "O Gott, schaffe in mir ein reines Herz" },
    { number: 431, name: "Brich mir das Lebensbrot, Du großer Herr" },
    { number: 432, name: "Lehre mich glauben, Herr, lehre mich flehn" },
    { number: 433, name: "In's Wasser fällt ein Stein (Ins Wasser fällt ein Stein)" },
    { number: 433, name: "Es fällt uns oft so schwer, mit Menschen auszukommen" },
    { number: 434, name: "Ich will den Herrn loben allezeit (Kanon)" },
    { number: 435, name: "Called unto holiness (Holiness unto the Lord)" },
    { number: 435, name: "Heilig dem Herrn!, das heißt: Kirche des Herrn (Heilig dem Herrn! ist die Losung)" },
    { number: 436, name: "Wer auf Gott vertraut (Denn Er hat Seinen Engeln befohlen)" },
    { number: 437, name: "Sicher in Jesu Armen, sicher an Seiner Brust" },
    { number: 438, name: "Du bist mein Zufluchtsort, Du bist mein Schirm, mein Gott" },
    { number: 439, name: "Gott will's machen, dass die Sachen" },
    { number: 440, name: "Der Herr ist gut, in dessen Dienst wir stehn" },
    { number: 441, name: "Lasset uns laufen durch Geduld" },
    { number: 442, name: "Du bist unsre Zuversicht. Du bist unsre Stärke" },
    { number: 443, name: "Gott wird dich tragen, drum sei nicht verzagt" },
    { number: 444, name: "Lasst uns miteinander (Kanon)" },
    { number: 445, name: "Ohne Weg, ohne Licht, ohne Hilfe (Seine Güte und Gnade und Seine große Treu)" },
    { number: 445, name: "A pilgrim was I (Surely goodness and mercy)" },
    { number: 446, name: "Zünde an dein Feuer" },
    { number: 447, name: "Befiehl du deine Wege" },
    { number: 448, name: "Himmel und Erde werden vergehn" },
    { number: 449, name: "Kommt doch her zu Mir" },
    { number: 450, name: "Amen! Amen! lauter Amen" },
    { number: 451, name: "Helfer der Schwachen, kehre Dich zu mir" },
    { number: 452, name: "Jesus, die Sonne, das strahlende Licht" },
    { number: 453, name: "Du bist Immanuel: Mit uns ist Gott" },
    { number: 454, name: "Weil Gott die Welt so unendlich liebt" },
    { number: 455, name: "Harre, meine Seele, harre des Herrn" },
    { number: 456, name: "Nimmst Du mich noch einmal an?" },
    { number: 457, name: "Alles, was atmet, alles, was lebt (Der See, der den Himmel spiegelt)" },
    { number: 458, name: "Herr, ich sehe deine Welt" },
    { number: 459, name: "Geh aus, mein Herz, und suche Freud" },
    { number: 460, name: "Wie groß ist mein Gott, kein andrer wie er" },
    { number: 461, name: "Ja, das ist Freude" },
    { number: 462, name: "Es gibt jemand, der deine Lasten kennt" },
    { number: 463, name: "Wenn ich bedenke, was der Herr getan" },
]
