import { Song } from "./Contents"

// SuG (s/S)
export const SuG: Song[] = [
    { number: 1, name: "Ach bleib mit deiner Gnade" },
    { number: 2, name: "All ihr Geschöpfe unsres Herrn" },
    { number: 2, name: "Kommt, preist Ihn! Halleluja!" },
    { number: 3, name: "Alle Ehre sei meinem Retter" },
    { number: 4, name: "Allein Deine Gnade genügt" },
    { number: 5, name: "Alles ist bezahlt (Jesus starb für mich)" },
    { number: 6, name: "Alles vergeben" },
    { number: 7, name: "Alles will ich Jesus weihen" },
    { number: 8, name: "Anker in der Zeit" },
    { number: 9, name: "Befiehl du deine Wege" },
    { number: 10, name: "Bei Dir, Jesus, will ich bleiben" },
    { number: 11, name: "Bleibend ist Deine Treu" },
    { number: 12, name: "Christus hält mich fest" },
    { number: 12, name: "Wenn mein Glaube schwinden will" },
    { number: 13, name: "Christus ist auferstanden" },
    { number: 13, name: "Seht, welch ein Morgen" },
    { number: 14, name: "Christus ist mein Herr" },
    { number: 15, name: "Christus sehn" },
    { number: 15, name: "Lass uns sehn" },
    { number: 16, name: "Danke, Jesus" },
    { number: 17, name: "Das alt rauhe Kreuz" },
    { number: 17, name: "Dort auf Golgatha stand" },
    { number: 18, name: "Dein Reich komme, Herr" },
    { number: 19, name: "Deine Gnade hat mich erwählt" },
    { number: 20, name: "Der Herr ist mein Hirte" },
    { number: 21, name: "Die Herrlichkeit des Herrn" },
    { number: 22, name: "Die Herrlichkeit von Golgatha" },
    { number: 23, name: "Dir, Dir, o Höchster, will ich singen" },
    { number: 24, name: "Dir gebührt die Ehre" },
    { number: 25, name: "Dir gehört mein Lob" },
    { number: 26, name: "Du bist erhoben" },
    { number: 27, name: "Du bist mein Zufluchtsort im Sturm" },
    { number: 28, name: "Du großer Gott" },
    { number: 29, name: "Du hast Erbarmen" },
    { number: 29, name: "Wer ist ein Gott wie Du" },
    { number: 30, name: "Du meine Seele, singe" },
    { number: 31, name: "Durch Dein Wort" },
    { number: 32, name: "Ehre sei Gott für immer" },
    { number: 33, name: "Ein feste Burg" },
    { number: 34, name: "Ein für alle Mal" },
    { number: 35, name: "Ein Gott, der redet" },
    { number: 36, name: "Er ist der Erlöser" },
    { number: 37, name: "Er lebt für immer, Amen" },
    { number: 37, name: "Komm und sing mit mir das Lied von der Befreiung" },
    { number: 38, name: "Erzählt von der Größe Gottes 8 Es gibt bedingungslose Liebe" },
    { number: 39, name: "Es ist Jesus" },
    { number: 39, name: "Welch ein Schatz" },
    { number: 40, name: "Fels des Heils" },
    { number: 41, name: "Für mich gingst Du nach Golgatha" },
    { number: 41, name: "Herr, deine Liebe ist so groß" },
    { number: 42, name: "Glaube an Jesus" },
    { number: 43, name: "Gott handelt" },
    { number: 43, name: "Mein Gott, ich trau auf Dich" },
    { number: 44, name: "Gott ist gegenwärtig" },
    { number: 45, name: "Gott von Ewigkeit" },
    { number: 45, name: "Du bist der wahre Hirte" },
    { number: 46, name: "Wie wunderbar ist Gottes große Liebe" },
    { number: 46, name: "Gottes große Liebe" },
    { number: 47, name: "Groß ist das Geheimnis" },
    { number: 48, name: "Größer als ich es verstehe" },
    { number: 49, name: "Großer Gott, wir loben Dich" },
    { number: 50, name: "Heilger Gott (The Gospel Song)" },
    { number: 50, name: "The Gospel Song (Heilger Gott)" },
    { number: 51, name: "Heilig, heilig, heilig (Herr, mein Gott und König)" },
    { number: 52, name: "Heilige mein Herz (Lehre mich, Herr)" },
    { number: 52, name: "Lehre mich, Herr" },
    { number: 53, name: "Herbei, o ihr Gläubigen" },
    { number: 54, name: "Herr, Dein Wille soll geschehn" },
    { number: 54, name: "Soll ich Segen von Dir, Herr, nehmen" },
    { number: 55, name: "Herr, weil mich festhält Deine starke Hand" },
    { number: 56, name: "Herrlicher Gott" },
    { number: 57, name: "Herz und Herz vereint zusammen" },
    { number: 58, name: "Ich bete an die Macht der Liebe" },
    { number: 59, name: "Ich bin durch die Welt gegangen" },
    { number: 60, name: "Ich bin entschieden zu folgen Jesus" },
    { number: 61, name: "Ich blicke voll Beugung und Staunen" },
    { number: 62, name: "Ich habe nun den Grund gefunden" },
    { number: 63, name: "Ich seh das Kreuz" },
    { number: 64, name: "Ich steh an Deiner Krippe hier" },
    { number: 65, name: "Ich will Dich anbeten" },
    { number: 65, name: "Licht dieser Welt" },
    { number: 66, name: "Im Glauben leben" },
    { number: 66, name: "Durch Glauben können wir verstehn" },
    { number: 67, name: "In Christus" },
    { number: 68, name: "In dem Kreuz liegt die Kraft" },
    { number: 69, name: "In Ewigkeit beim Vater" },
    { number: 68, name: "Welch ein dunkler Tag" },
    { number: 69, name: "Christus, Du bist der Herr" },
    { number: 70, name: "In mir lebt Hoffnung" },
    { number: 71, name: "Ist Gott für mich, so trete" },
    { number: 72, name: "Jauchzet, ihr Himmel, frohlocket, ihr Engel" },
    { number: 73, name: "Jesus, höchster Name" },
    { number: 74, name: "Er ist der Friedefürst" },
    { number: 75, name: "Jesus ist kommen" },
    { number: 76, name: "Jesus, Mitte meines Lebens" },
    { number: 77, name: "Jesus, zieh zum Kreuze mich" },
    { number: 78, name: "Kann es denn sein" },
    { number: 79, name: "In keinem Namen sonst" },
    { number: 79, name: "Kein Name sonst" },
    { number: 80, name: "Komm, Du Quelle " },
    { number: 81, name: "Kommt, preist und lobet unsern Gott" },
    { number: 82, name: "König Jesus (Jesus, Weg der Wahrheit)" },
    { number: 82, name: "Jesus, Weg der Wahrheit" },
    { number: 83, name: "Krönt Ihn, krönt unsern Herrn" },
    { number: 84, name: "Lobe den Herren, den mächtigen König" },
    { number: 85, name: "Wer diesem Felsen fest vertraut" },
    { number: 85, name: "Mein Glaube fest sich bauen kann" },
    { number: 86, name: "Mein Jesus, ich lieb Dich" },
    { number: 87, name: "Mein Mund besinge tausendfach" },
    { number: 88, name: "Mir ist Erbarmung widerfahren" },
    { number: 89, name: "Näher, mein Gott, zu Dir" },
    { number: 90, name: "Nicht uns" },
    { number: 91, name: "Nun danket alle Gott" },
    { number: 92, name: "Nun gehören unsre Herzen" },
    { number: 93, name: "Nur das Blut des Lammes Jesu" },
    { number: 94, name: "O die tiefe Liebe Jesu" },
    { number: 95, name: "O du fröhliche" },
    { number: 96, name: "O Gnade Gottes" },
    { number: 97, name: "O Gott, Dir sei Ehre" },
    { number: 98, name: "O Haupt voll Blut und Wunden" },
    { number: 99, name: "Mein Herr und Gott" },
    { number: 99, name: "Schau auf den Herrn" },
    { number: 100, name: "Jesus, komm, schein in unsre Nacht" },
    { number: 100, name: "Schein in unsre Nacht" },
    { number: 101, name: "Seht unsern Gott" },
    { number: 102, name: "Sei gnädig, o Herr" },
    { number: 103, name: "Seligstes Wissen" },
    { number: 104, name: "Sieh, das Lamm Gottes" },
    { number: 105, name: "Siehst du das Lamm" },
    { number: 106, name: "So groß ist der Herr" },
    { number: 106, name: "Ein König voller Pracht" },
    { number: 107, name: "So nimm denn meine Hände" },
    { number: 108, name: "Soli Deo Gloria" },
    { number: 108, name: "Allein zu Deiner Ehre" },
    { number: 109, name: "Sonne der Gerechtigkeit" },
    { number: 110, name: "Sprich, o Herr" },
    { number: 111, name: "Stern, auf den ich schaue" },
    { number: 112, name: "Vater, komm und lehre Du uns" },
    { number: 113, name: "Vereint" },
    { number: 113, name: "Wir sind vereint" },
    { number: 114, name: "Von guten Mächten treu und still umgeben" },
    { number: 115, name: "Vor Gottes Thron" },
    { number: 115, name: "Im Himmel dort vor Gottes Thron" },
    { number: 116, name: "Vor Grundlegung der Welt" },
    { number: 117, name: "Was Gott tut, das ist wohlgetan" },
    { number: 118, name: "Weiß ich den Weg auch nicht" },
    { number: 119, name: "Welch ein Freund ist unser Jesus" },
    { number: 120, name: "Welch ein Tag" },
    { number: 120, name: "Der größte Tag für alle Zeit" },
    { number: 121, name: "Wenn Friede mit Gott" },
    { number: 121, name: "Mir ist wohl in dem Herrn" },
    { number: 122, name: "Wenn ich, o Schöpfer" },
    { number: 123, name: "Wenn nach der Erde Leid, Arbeit und Pein" },
    { number: 124, name: "Wie groß bist Du" },
    { number: 125, name: "Wie tief muss Gottes Liebe sein" },
    { number: 126, name: "Wir sehnen uns nach Dir" },
    { number: 126, name: "Jesus, Sohn des Höchsten" },
    { number: 127, name: "Gemeinsam kommen wir zu Dir" },
    { number: 127, name: "Wir sind Gottes Kinder" },
    { number: 128, name: "Wo ich auch stehe" },
    { number: 129, name: "Woher wissen wir" },
    { number: 130, name: "Herr, wohin sonst" },
    { number: 130, name: "Wohin sonst" },
    { number: 131, name: "Wunderbar großer Erlöser" },
    { number: 132, name: "Wunderbarer Hirt" },
    { number: 132, name: "Du bist ein wunderbarer Hirt" },
    { number: 133, name: "Wunderbarer König" },
    { number: 134, name: "Würdig das Lamm, das geopfert ist" },
    { number: 135, name: "Würdig ist das Lamm" },
    { number: 135, name: "Danke für das Kreuz" },
    { number: 136, name: "Komm und lobe den Herrn" },
    { number: 136, name: "Zehntausend Gründe" },
]
